### ISSUE TITLE
RFC: The Case of Densified LOX (dLOX)

### ISSUE THREAD

**Issue by rogersk** [KSP-RO/RealismOverhaul#1210]
## dLOX technology

Cooling liquid oxygen from the "standard" sub-boiling temp of 90K down to 68K has shown a ~9% saving in volume.

The densified oxidizer filling was tested in real scale in 2000, for the X-33 tanks[1], and is currently deployed in the Falcon9 v1.2[2]. Expanding use of this technology is to be expected.

D(LOX)= 0.001141 (as used in CRP/RF)
D(dLOX)= 0.0012489 [3]
## in KSP

The density is a property of the tank, rather that of the engine - oxygen temp stratifies in the tank. Outflow can be considered to be the usual 90K

```
RESOURCE_DEFINITION
{
    name = denseLqdOxygen
    density = 0.0012489
    .... // keep all other properties of LOX
}
```

An _engine-transparent mechanism_ would be ideal, possibly allowing retro-fitting older rockets for KSP purposes. Using a "free resource conversion" of 1:1 dLOX => LOX.
## Possible Integrations

a) standalone `ResourceConverter` - increases part count, requires redesigning, no further patches needed
b) tank-integrated `ResourceConverter` - cleanest solution, but requires patching all supported tanks
c) engine-integrated `ResourceConverter` - hacked, but all engines need to patched + the converter rate has to be adjusted to keep up with maximum engine inflow (if >1.0)
d) "magic" `ResourceConverter` - LOX 0.91:1
e) clipping ('virtual' and not really practical)

---

[1] http://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20050203875.pdf
[2] http://www.b14643.de/Spacerockets_2/United_States_1/Falcon-9/Description/Frame.htm
[3] http://oxygen.atomistry.com/liquid_oxygen.html

**Comment by kiwivogel** [comment]
That, or you can cheat by abusing the 'tank utilisation' slider. But that would cut corners on issues like warming up too much and stuff. Also I think denser propellant increases performance a little since you throw more mass out the back if you can fit more mass through the same engine? I'll think about this some more.

**Comment by rogersk** [comment]
the engine sees the oxidizer in gaseous form, regardless of storage in the tank.
It only affects the amount of "usable quantity" in the tank. A dLOX tank will hold 9% more units compared to the same tank filled with regular LOX.

**Comment by kiwivogel** [comment]
Yeah, ok but it's not gaseous in the turbopump yet right?

**Comment by rogersk** [comment]
already the outflow from the tank is regular LOX, so outside of the tank everything is the same.

**Comment by rogersk** [comment]
the question is, which implementation type would be most "in line" with the RO philosophy.

**Comment by kiwivogel** [comment]
Alternative: work with densities, give tanks a volume and list contents in weight?

**Comment by stratochief66** [comment]
Most in line with RO philosophy would probably be to add it as a new resource with a new density. Any engines allowed to burn it would need to be rated for it, and have it specifically added to their config files with the appropriately recalculated mixing ratio.

Given that the Soviets also used (or planned to use) densified propellants in an N1 varient and did/do use it on the Soyuz-U, this is an issue that we need to give a fair mulling over.
http://www.astronautix.com/lvs/soya511u.htm

Because the desnity change is sufficiently small (9%?) that is within the range of the Utilization slider, and that could be manipulated for now in most cases, as it defaults to 84% or so IIRC.

@NathanKell ?

Best way to implement/integrate densified propellants into RO?

**Comment by SirKeplan** [comment]
One problem with implementing densified propellants is density/temperature is not a discrete thing, Modern Falcon 9s use densified prop, but the exact amount of prop they fit in seems to be slightly variable, and of course the propellant will warm up if the rocket stays fueled on the pad for too long.

Antares used densified lox, as it used NK33s on the first stage. the new antares will use regular LOX with the RD-181 as far as i know.

According to spaceflight101, Merlin uses LOX cooled down to as low as –207°C, the N-1 used temps of around -192°C, and Antares temps of -195°C

**Comment by stratochief66** [comment]
@SirKeplan good point. 

That could be something RealFuels might be able to handle in the future? instead of boil-off/phase transition deleting a resource, it could take steps down the ladder i.e denisified -> stdLox -> gaseousLox -> lostLox

**Comment by rogersk** [comment]
btw, the density gain in antares/soyuz is <5%
falcon also uses chilled RP-1 (-7C) which yields ~3%. this again leads to modified tank volumes, to maintain the fuel mix ratio.
(densified methane will most probably follow suit)

Do we assume that a regular engine cannot be employed to use a dLOX tank? Letting it warm up in the flow cycle, in contrast to what the NK33/AJ26 did (it required the lower temperatures for its operation). It's unclear to me whether the Merlin "needs" the dLOX or is able to perform nominally with regular LOX. 

Other approaches?

"no way" - it's not worth at this time.

"no change" - densification is purely virtual, kept for the imagination, or self-restrain of the user (using utilization or other means of regulating tank capacity). Engine keeps all its original performance spec, regardless of the physical tuning of fuel. So building a ksp replica of the falcon will result in less payload capacity, due to less fuel in the same volume.

"modified utilization" - the slider will allow values above 100% to represent sub-cooled density gains - possible implementation problems + different gain curves/limits for different substances.

This leads me back the concept of the "magical resource converter" (either as standalone or tank patch), which could be used to multiply the output mass. i.e. tunable scale of 101-110% for a "LOX subcooled assembly". It could also employ a negative temperature efficiency factor, for time/temp  dynamics.

**Comment by stratochief66** [comment]
@rogersk 

The way RealFuels and RO configs work, if dLox is going to have any properties different than regular Lox, it would be a different resource. Particularly in terms of density, given that KSP uses volume fuel ratios unique configs for engines using the fuel would be needed to handle that. You asked what method of implementation would be the most 'in line' with RO philosophy (and practice), and that is what I answered (in my opinion)

I think it is an idea worth considering for a number of reasons. I don't think we need a magical resource converter, I think if the use of densified fuels is to be included in RO it would be part of RealFuels or one of the existing RO mods.

@rogersk, I would suggest to 'chill' (intended pun!) on this topic until NathanKell has had a chance to weigh in.

**Comment by rogersk** [comment]
@stratochief66 cool :)

**Comment by SirKeplan** [comment]
@rogersk as far as i can tell it varies whether an engine requires densified prop or not. the Merlin 1D originally was flying with regular LOX, but they upgraded the Falcon to take denser prop, but kept the engines mostly the same, if the Merlin 1D was changed apart form uprating it was pretty minor.

It seems however that the NK33 is an engine that requires denser lox. "The NK-33 requires sub-cooled Oxygen with a temperature below its boiling point of -183-degrees Celsius to cool the turbopump bearings that would otherwise fail" from http://spaceflight101.com/spacerockets/soyuz-2-1v/

**Comment by NathanKell** [comment]
Done in RO v16.
