### ISSUE TITLE
Create a new OP for the KSP forum

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RealismOverhaul#1226]
Old OP:

http://forum.kerbalspaceprogram.com/index.php?/topic/90151-112-realism-overhaul-v1100-may-8/

Link to new OP candidate:

http://forum.kerbalspaceprogram.com/index.php?/topic/90151-112-realism-overhaul-v1100-may-8/&page=147#comment-2569540

Actual new OP. Thanks for all the help!
http://forum.kerbalspaceprogram.com/index.php?/topic/140070-112-realism-overhaul-v1101-may-18/#comment-2589963

**Comment by stratochief66** [comment]
Are all these mods still 'suggested' ? Do some of them even exist anymore? Should others be added that we have added compatibility for? Do the links for each of them still work or do they need updating? 

6S Service Cmpt link
AIES Aerospace~ link
ALCOR* link
ATK Propulsion Pack
Atomic Age link
Community ISS* link
Component Space Shuttle* link
DMagic Orbital Science link
FASA~ link
KAS link
KW Rocketry~ link
LazTek SpaceX~* link
LionHead Landers & Probes* link
LionHead ESA (no Ariane 6)* link
Near Future Tech~ link
OLDD Apollo~* link
Porkworks Habitation link
Proton - OLDD~* link
Real Scale Boosters
RLA Stockalike~ link
Rocketdyne F-1~ link
SCANsat link
Soviet Engines~ link
RN Antares-Cygnus~ link
RN Proton & Soyuz R7~ link
RN Salyut/Soyuz/Vostok/Voskhod~ link
RN Skylab link
RN Solar Panels link
RN Soviet Probes~ link
RN US Probes Pack~ link
Soyuz - BobCat link
SpaceFactory Vostok/Voskhod~ link
SXT~ link
Taerobee~ link
Tantares~ link
Tantares LV~ link
Universal Storage link
Ven's Stock Revamp~ link

**Comment by SirKeplan** [comment]
**Supported Mods not listed:**
SSTU
CryoEngines

**Comment by Zarbizaure** [comment]
also, it would be very kind to list frogotten real engines - it does not add a lot but I made it RO-supported, though is not supported through RO's files overwriting system.

**Comment by NathanKell** [comment]
Yes! We totally should list FRE! It's great!

I concur on RSB, SSTU, CryoEngines, FRE. And stripping the Rocketdyne F-1 link. I believe we also dropped support for OLDD Proton because of collider issues.

**Comment by Zarbizaure** [comment]
@NathanKell thanks! 
I did never played with OLDD mod, but colliders issues are indeed a problem that we cannot fix on our side so that makes sense.

**Comment by stratochief66** [comment]
So, New To Add:
Real Scale Boosters (RSB) - Need A Link
SSTU - Need A Link
CryoEngines - Need A Link
Forgotten Real Engines (FRE) - Need A Link

**Comment by Zarbizaure** [comment]
Real Scale Boosters (RSB) - [Link](http://forum.kerbalspaceprogram.com/index.php?/topic/130776-112-real-scale-boosters-013-2016-05-05/)
SSTU - [Link](http://forum.kerbalspaceprogram.com/index.php?/topic/117090-wip112-sstulabs-low-part-count-solutions-orbiter-landers-lifters-dev-thread-05-07-16/)
CryoEngines - [Link](http://forum.kerbalspaceprogram.com/index.php?/topic/106089-10511-cryogenic-engines-high-isp-chemical-rockets-11-test-release/)
Forgotten Real Engines (FRE) - [Link](http://forum.kerbalspaceprogram.com/index.php?/topic/134585-112wip-forgotten-real-engines/&page=1)

Linky linkely links ~

**Comment by dxdy-name** [comment]
Permalink to the placeholder to develop the formatting for the new OP: http://forum.kerbalspaceprogram.com/index.php?/topic/90151-112-realism-overhaul-v1100-may-8/&page=147#comment-2569540

**Comment by stratochief66** [comment]
@Zarbizaure the existing OP contains forum links, which I think work fine, as those will in-turn link to their Githubs generally, where the reverse is not true.
And thanks for tracking them down so quickly :) @dxdy-name, take the links from just above you :)

**Comment by Zarbizaure** [comment]
you're welcome!
Also, if you update the forums links, then the CKAN supported list could be updated too (although SSTU is not on CKAN yet).

**Comment by PhineasFreak** [comment]
The OLDD Apollo, although it is patched for the latest versions (and it is RP-0 compatible), suffers from the same collider issues as the Proton pack. I would suggest to also remove it from the list.

**Comment by dxdy-name** [comment]
Have looked through them all and arrived at the list above. For things listed under "?:" I would require further guidance, as it's not clear from their forum threads whether they're still active/supported.

**Comment by raidernick** [comment]
Spacefactory doesn't even have RO configs anymore I believe they were removed because the mod is dead and has bad colliders preventing the parts from working.

Many of bobcats parts have bad colliders and can't be used anymore without either replacing the part with a stock one or just not using them at all. The soviet engines are fine, the collider problem is very evident in american pack and his soviet rockets. These parts will also never be updated as dragon01 is working with decq on brand new parts for a new mod and ditched that one, but since he is banned the mods refuse to lock his thread so it remains active despite never going to be fixed.

Lionhead mods are dead, many of the crafts don't work at all anymore because they relied on the cleverbobcat dll or w/e it was called, cause massive null refs now. Also many parts have collider problems

**Comment by jwvanderbeck** [comment]
Is this part packs only? Seems to be a lot of mods missing from the new proposed list.

**Comment by NathanKell** [comment]
@jwvanderbeck I believe it is only the 'suggests' listing, the required and the recs would not be changing.

**Comment by dxdy-name** [comment]
I put a first draft into the forum comment linked at the top. What I changed:

- Combined the current most important changes section with the one in the wiki
- Renamed the info-section into "Getting Started" and slightly reformulated
- Removed the mod list google sheet that's currently linked there. On this, feedback would be particularly helpful: Who currently maintains this sheet? Is it still current?
- Put the installation section above the performance section, that makes more sense
- Updated the text in the installation slightly, removing the comments about CKAN being new
- Changed the formatting in that section to better represent the distinction between the two alternative modes of installation (manual and CKAN)
- Moved the contributors section slightly downwards, so that there are two paragraphs explaining what the mod is for people reading the thread for the first time in front of it. 
- Put the performance-tweaks related screenshots into spoilers to save a bit of space
- Reorganized the performance tweaks section to better reflect a normal optimization progress. It now recommends first checking that the game is running in 64-bit, if possible, then trying lossless optimization (ie Dynamic Texture Loader, opengl-mode) and after that trying to remove parts.
- Removed colour coding from dependencies in the mod-list. There's no point in saying "this mod is particularly recommended," when it is in fact a hard depenendcy anyways.
- Introduced distinction between mods that are purely part mods and mods that provide new mechanics into the suggested section. It's quite a lot of mods there so this should help people to get a better overview of the different kinds of things they can add.
- Moved the explanation of the color-coding so that it's on the screen with the section where it is used. This seems better than forcing people to scroll back up, if they've only skimmed the previous text section.
- Simplified the formatting of the color-coded modlist (green is now only green instead of green underlined, orange is orange instead of orange italics)
- Simplified the formatting of titles, they are now distinguished by size and bold-ness instead of color and underline. Also removed trailing :'s from captions.
- Changed font sizes to be more consistent overall
- Used links over the actual text in the modlist instead of having small hard-to-click links after the mod name

Feedback would be appreciated.

**Comment by stratochief66** [comment]
Thanks again! i will update this comment when I've had a chance to look it over. Pinging @NathanKell to take a look and provide feedback as well.

**Comment by NathanKell** [comment]
@dxdy-name Took a look! Thanks!

Some suggestions:
* "Realism Overhaul does this by combining and configuring other mods, and mod and stock parts, ..."
* Change the first bullet to mention 10x Kerbol System (or other resizes) are also supported. We don't require RSS per se. Though I think that might have come from our wiki and should be fixed there too :D
* There must have been some good new ablums -- maybe @winged7 has some good pics? Pingopete's imgur account does too, as does mine and many others'.
* Rework the Performance Tweaks section now that we're in x64 land.
* Ending should state that it's currently maintained by strato and SirKeplan and me I think. Since we're the active folks with 'can merge commits' access.

Apart from the mod changes mentioned above.

**Comment by leBenti** [comment]
Hi Guys,

I'm still trying to figure out how to be most efficient in contributing here. I thought about making a spreadsheet where every engine and their real world pricing will be listed. Now is the list that @stratochief66 provided the current working version? I could then compare the engines from the different part packs with the techtree from RP-0 and track down which engine is not listed yet and which one is. 

Just let me know, I'm off to work now, but I'll make sure to read the latest developments here :)

**Comment by winged7** [comment]
> There must have been some good new ablums -- maybe @winged7 has some good pics?
> 
I would like to reccomend the following albums:

http://imgur.com/a/e87nC - Manned Venus Flyby
http://imgur.com/a/PBccu - X-20 Dyna-Soar
http://imgur.com/a/DghGg - X-15 & B-52
http://imgur.com/a/HCxgI - Bell X-1 & B-29
http://imgur.com/a/fNMv2 - New Horizons
http://imgur.com/a/IiL15 - Venera 9
http://imgur.com/a/Kpn60 - Falcon 9, Falcon Heavy, Saturn IB, Atlas V, Titan IV

http://winged7.imgur.com/

**Comment by dxdy-name** [comment]
Re: Images

I think those would be a reasonable mix: http://i.imgur.com/drCs9bs.jpg
http://i.imgur.com/B3CbpFn.png
http://i.imgur.com/XACuUbw.png
http://i.imgur.com/DtsiqR1.png
http://i.imgur.com/UCHLc8q.png
http://i.imgur.com/GKooMAT.png
http://i.imgur.com/HL95Hkl.png
http://i.imgur.com/l5WLZw0.png

For obvious reasons, it'd be better if @stratochief66 or @NathanKell would create the actual Imgur-Album though. 

I changed the ending and removed the bullet point about RSS (it makes little sense to list "you can use any solar system you please" as a major chance for RO). 

Pursuant to the clarification in IRC, I removed the PerformanceTweaks section.

**Comment by NathanKell** [comment]
I would suggest a mix of replica and user-created craft pictures. I think with only those pictures, it might appear we're focused on replicas only.

**Comment by raidernick** [comment]
you can use anything from my imgur albums: http://raidernick.imgur.com/

**Comment by dxdy-name** [comment]
@NathanKell How about this mix. That would give a couple of images in the VAB, focussing on the own rockets while still keeping the beautiful earth/venus pictures of winged7. With @raidernick's skylab it'd also include a station.:

http://i.imgur.com/drCs9bs.jpg
http://i.imgur.com/B3CbpFn.png
http://i.imgur.com/XACuUbw.png
http://i.imgur.com/DtsiqR1.png
http://i.imgur.com/UCHLc8q.png
http://i.imgur.com/GKooMAT.png
http://i.imgur.com/HL95Hkl.png
http://i.imgur.com/l5WLZw0.png
http://i.imgur.com/Y34aDIZ.png
http://i.imgur.com/kzSgp9r.png
http://i.imgur.com/B4fL6Xg.jpg
http://i.imgur.com/DG0dSQv.jpg
http://i.imgur.com/UeFt4lZ.jpg

**Comment by Zarbizaure** [comment]
I'm pretty sure some of my dev pictures could also represent well RO:
http://imgur.com/a/AWtiZ

**Comment by NathanKell** [comment]
I will construct the album and update the OP for next RO release. However, a question: is it worth getting it in someone else's name so someone other than me can edit it?

**Comment by stratochief66** [comment]
Probably. Either using SirKeplan or my name makes sense, or Agathorn or
Regex if they are interested. Basically, someone who is around regularly.

I'm assuming having it under NathanKell's name is particularly bad because
he has super-forum powers, and is also over busy as is? If the OP was under
SirKeplan or my forum name, would that have any advantages such as allowing
other people to also edit it, or no? I am entirely ignorant of how forum
rights work.

**Comment by dxdy-name** [comment]
Forum thread done, this issue probably ought to be closed.

**Comment by NathanKell** [comment]
Just so! :)
