### ISSUE TITLE
RD-275 tech and cost rebalance.

### ISSUE THREAD

**Issue by shimmythejj** [KSP-RO/RealismOverhaul#1322]
RD-253/RD-275 Engine. All configurations unlock at the same time, and cost appears to be unbalanced (lower than it should be)

Vens part unlocks at staged combustion

**Comment by SirKeplan** [comment]
Initial cost looks [ok to me](https://github.com/KSP-RO/RP-0/blob/master/tree.yml#L1968) , the later configurations could do with placing though.

**Comment by shimmythejj** [comment]
I might not understand the intended pricing methodology, though comparing the RD-253 to an engine of similar class (thrust) like the LR87 base config, The RD-253 has 1/10 more thrust, 2/3 the mass, significantly better SL and Vac ISP, but has 1/3 the cost of the LR87, 515 vs 1550. The only downside of the RD-253 is that it is a single chambered engine with no built in roll authority.

**Comment by SirKeplan** [comment]
Yeah, the pricing is one of those problems that appear when we have both US and Soviet engines. Soviet engines generally have a much lower price, and a much greater performance. This is partly because of the soviet economy, and the fact that they often mass produced parts much more than the USA did.

see https://github.com/KSP-RO/RP-0/issues/490 for some of our discussion on this.

**Comment by NathanKell** [comment]
For now we can add some nominal extra cost for the later configs, and at least place them correctly.

It's also worth noting that the balancing only comes to the fore with TestFlight, since, well the early Proton was not exactly known for reliability.
