### ISSUE TITLE
PROPOSAL: Deliver "stock" Realism Overhaul example craft with install

### ISSUE THREAD

**Issue by Theysen** [KSP-RO/RealismOverhaul#1331]
Just a little thought about creating example craft files for RO / RP-0 installs. It would generally offer a chance (and especially for new users) to get an idea of the mod suite without the need to install thousands of very specific part mods. The former suggests to create a few vessels using mostly the procedural stuff and stock engines. (To be honest though, the current craft load menu is not that encouraging to  do so as RO comes with all the mod crafts aswell so the example crafts would need a proper designator in front of their names - until KSP might do something about better organization :) )

If there is basic interest / positive feeling it might be useful, please feel free to add your ideas to a first framework of vehicles. 

I'd tend to do a little mix of both replica-like craft and custom vehicles. Once there is a proper selection we could build a first pass of vehicles and continue from there. 

***\* I'll add up the proposals to this first post IF you think there is actual use in the whole idea. ***\*

**Comment by jwvanderbeck** [comment]
I'm actually against this, as I want to see NO craft included in the install.  Instead we should be splitting sample craft out into a separate package that is an optional install either manually or through CKAN.

If we split them out into a separate package, then it would make sense to in fact do a few packages.  One for stock craft like you say, and then others for different part packs.

Right now RO is spammed full of RN sample craft which should really be distributed with RN's packs not RO.

**Comment by raidernick** [comment]
@jwvanderbeck RO craft files should absolutely NOT be distributed with stock packs....that's a stupid idea. I, and other modders get enough bogus support requests without a bunch of morons whining about loading up craft files in stock and having all the parts be floating around since they stupidly used the RO ones, so unless you will be providing support for this I'm not doing it. 

@Theysen is right it should be a separate mod that is recommended, or ideally KSP should hide craft files that you don't have the parts for like it does with subassemblies so the list isn't spammed. For now though I can combine the SHIPS and SUBASSEMBLIES folders into a crafts parent folder so when you install RO it doesn't install any crafts by default.

**Comment by raidernick** [comment]
I made a PR for it here https://github.com/KSP-RO/RealismOverhaul/pull/1332

**Comment by Theysen** [comment]
@jwvanderbeck 

The additional "add-on" for craft files is a good solution aswell! That's why I asked to leave your thoughts. 
Although IF we drag out the mod craft files-like raidernick has already started with- it wouldn't be such a hassle to have a few stock craft as starters. 

(In my head there is an intelligent Craft File System built in KSP where you can have different tabs with different vessel types and mods etc,etc,etc. making this stuff not important anyways..)

**Comment by jwvanderbeck** [comment]
@raidernick 
> RO craft files should absolutely NOT be distributed with stock packs....that's a stupid idea. I, and other modders get enough bogus support requests without a bunch of morons whining about loading up craft files in stock and having all the parts be floating around since they stupidly used the RO ones, so unless you will be providing support for this I'm not doing it

Either you, or I am misunderstanding Theysen's request.  When we say "stock" I think we mean RO without extra part packs.  In other words, just the parts that come with a default install of RO and required mods.

**Comment by raidernick** [comment]
@jwvanderbeck which is exactly why I made a PR to separate the craft files into their own ckan mod that you can opt to install when installing RO

**Comment by jwvanderbeck** [comment]
Yes which satisfies *my* complaint, but not Theysen's original request which you seemed to be against.

**Comment by Schnobs** [comment]
Prebuilts are good documentation. With some of the more fine-grained part packs, it's at times challenging to figure out which part goes where, and near-impossible to be certain that you haven't missed a piece. Even though I'm quite familiar with FASA I'm not sure if I could properly piece together a full Apollo CM+LM+LV. Raidernick's strike me as even more fine-grained.

I'm quite in favor of having prebuilts, and IMO every non-trivial part pack should have some and install them by default. Make it as easy as possible for every user to have a look -- if they don't like or need it they won't look again (or at all) and that's that.

IMO, the main problem is the lack of organization. The list clutters the menu, and KSP pre-loading every eligible vessel can cause quite noticable delays. This causes me to turn off stock craft altogether, only turning it on again if I'm a) really at a loss and b) think of the option at the time.

But that's not the fault of any mod, and unlikely to be solved by mods.

For the time being, it would help if the prebuilts came with their respective part packs, filtered for RO/Stock if possible.

**Comment by stratochief66** [comment]
@raidernick , @NathanKell could either of you shed a little light on the current state of separating craft files into a separate CKAN option?

@Theysen I think at least half of us think this is a good idea (stock/proc rockets), although it shouldn't be part of the RO download (as no craft files should be, ideally) perhaps a craft sharing thread would be a good place to accrue excellent craft until we get the CKAN-craft thing sorted? I attempted to start an RO/RP-0 craft sharing thread many months ago, and promptly abandoned/forgot it due to lack of interest.

**Comment by raidernick** [comment]
@stratochief66 it's already been handled. The PR is ready here and as soon as @NathanKell is ready to make a RO release the netkan file will be changed over on the netkan git, nothing else needs to be done except making that RO release.

**Comment by stratochief66** [comment]
Still probably a good idea. Ultimately, probably best managed with a separate repo/distribution. Also, someone will still have to make them.

@Theysen , ok to close?
