### ISSUE TITLE
MMH & MONX as an option for RCS

### ISSUE THREAD

**Issue by PhineasFreak** [KSP-RO/RealismOverhaul#1369]
Currently we can use MMH and NTO as an option for the RCS but most real bipropellant thrusters use Mixed Oxides of Nitrogen (MON) since:

* They have lower freezing points.
* They are less corrosive.

MON1 and MON3 are the most used oxidizers (MON1 for the European thrusters, MON3 for the American).

**Comment by Theysen** [comment]
Funny enough, we just had this proposal in the IRC chat a few days ag whether to add them or not. I think it would be a good addition because many recent part packs come with the MON3 configuration for RCS thrusters and needing another tank to just have fuel for an engine which runs on MMH/NTO because the stock configs miss MON as an option is kind of counterintuitive.

**Comment by PhineasFreak** [comment]
Exactly that is my reasoning behind that proposal. I was configuring the new ProbesPlus parts and i found myself trying to adapt some bipropellant thrusters to work with both the generic RCS options that the satellite buses provide and the propellant requirements by the thrusters themselves. In the end i just made alternate engine configs that use NTO instead of MONX...

The MONX option(s) will require new cost and Isp multipliers and unfortunately i have no idea how these were calculated in the first place.

Another nice option would also be the Hydrazine + NTO/MONX but this is probably less useful.

**Comment by stratochief66** [comment]
Agreed, merging PR now.

**Comment by PhineasFreak** [comment]
OK, since it is now merged i will close this issue now.
