### ISSUE TITLE
Suggestion: Multiple mixture ratios for J2 engine

### ISSUE THREAD

**Issue by rsparkyc** [KSP-RO/RealismOverhaul#1497]
In doing some reading, I learned that mid-flight, they would alter the mixture ratio of the J2 engine to be slightly fuel-rich, which (IIRC), due to the extra hydrogen in the exhaust gasses, caused the engine to operate more efficiently.  You can see it charted here (Look for EMR Shift, after Center engine cut off): https://upload.wikimedia.org/wikipedia/commons/2/2c/Apollo17_Ascent_Trajectory.pdf
Might it be worth having an option to "switch modes", similar to how jet engines have afterburner (or the RAPIER can switch?)

**Comment by stratochief66** [comment]
It has been talked about. If you can find a way to implement it in a user friendly way, definitely go for it. In past RO IRC discussions though, I don't think we ever thought of a method that would make implementation worthwhile to the developer or the user.

In practice, I think this would have to be an entire mode of its own. What is happening is that the computer controlling the EMR shift has an idea of how much of propellant and oxidizer are left, and adjusted the mixing ratio so that both tanks will drain to empty at the same time. So, the mod would have to do the same thing. Leaving it to the user to change manually change the mixing ratio 'at the right time' would leave an excess of one or the other, which is the exact opposite goal of such a system.

**Comment by rsparkyc** [comment]
Yeah, I was thinking about how to do this properly, and realistically.

**Comment by PhineasFreak** [comment]
This should be part of RF. Ideally, a toggle (user-defined) would switch between a standard O/F ratio (the one defined inside the engine config - currently used) and an ideal O/F ratio (based on the amount of each propellant).

**Comment by rsparkyc** [comment]
There would need to be checks to make sure you're not burning a LOX rich mixture, or probably even a mixture that's LOX richer than the standard O/F ratio (or add a TF config that melts the engine if you do).  I'm assuming to program this, you need a few things:
1) the thrust at varying O/F ratios (for the J2 that's 1,000 kN at 5.5:1 and 780 kN at 4.5:1
2) the vac/atmos ISPs at each ratio (I know at 5.5:1 it's 421/200, but I have no idea about other ratios)
3) fuel consumption rates (when the ratio is changed, is more H2 being injected? Is less OX being injected? Is it a combination to maintain the same fuel flow rate?)
4) How do you update the RF config to give it your "extra fuel"?
5) I'm sure this would screw with deltaV readouts by both MechJeb and KER

You could probably have the engine configured with 2 different O/F ratios (starting and final, where final is always richer than starting), and have the engine be on "auto" mode, where it will switch to the secondary O/F ratio once you've burned through your remaining O/F ratio matches your final ratio.

**Comment by rsparkyc** [comment]
I guess I should mention that I closed this because I support it now with this mod: https://github.com/rsparkyc/EMRController/
