### ISSUE TITLE
TACLS base electricity consumption

### ISSUE THREAD

**Issue by PhineasFreak** [KSP-RO/RealismOverhaul#1509]
TAC Life Support includes the **BaseElectricityConsumptionRate** and **ElectricityConsumptionRate**  parameters. These define the EC needs for a single crew and works like the other LS parameters (food, water, oxygen etc) and it is currently set to zero by RO.

From the RO configs for crewed parts, a generic consumption rate is **200W/crew**. This translates to a consumption rate of **0.0556 Wh/crew/s** or **4.8 kWh/crew/day.**

This would allow the removal of the ModuleGenerator hack (really bad in my opinion) and allow a realistic electricity model for all crewed parts. For example, the Mk2 Pod only consumes power for the communications and the avionics but it is supposed to support 3 crew for at least 9 days. Use that battery power that is included with the parts!

Thoughts?

**Edit 1:** @JPLRepo why was thes parameters were set to zero in the first place? Is there a problem with TACLS and the EC generation/consumption model?

**Edit 2:** setting the **ElectricityConsumptionRate** to **0.2 (200 Watts)** does the trick, although the carried battery capacity does not cover a full day (Mk2 Pod testing).

**Comment by stratochief66** [comment]
@PhineasFreak NathanKell and I (and others) discussed and set this to zero 6-10 months ago. The reason is, RO is strongly used for historical craft, and the power consumption of LS systems varies widely over those craft, both between eras and nations.

For example, our historical research (probably) showed Mercury consumed 530W, so:
https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/FASA/RO_FASA_Mercury_Pod.cfg#L181

Gemini has two people, and keeps them alive for longer by providing more services, our research of historical sources (probably) resulted in the value you see here of 2090W:
https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/FASA/RO_FASA_Gemini_Pod.cfg#L287

I say (probably) here, because unfortunately we didn't always have as high of goals for documenting our sources as we aim for today. We've found a number of sources for these values over time, resulting in variations and adjustments, which themselves spawn other adjustments because other conditions need to be satisfied (mass of craft/consumed resources, historical actual durations, etc.) 

Anyway, we can discuss the above further if you like, but I think the goal makes sense, that is, to have a generic value for parts that have not been set to conform to historical data. I think having a default would make sense, but we'd have to have a way to make that not apply to parts that we've tagged/flagged as preConfigured or something like that. That would probably require a change to see and adjust according to the flag from TACLS's side, but hopefully that would be a small change.

TACLS could benefit from lots of 'little' changes that I should probably request over on the TACLS Github, and I'd be entirely understanding if they won't be implemented due to difficulty/lack of time. It would be nice if TACLS could keep accurate track of the battery life of craft, as it currently attempts for LS resources. It would be nice if TACLS took into account converters/fuel cells, that will generate electricity or create/convert LS resources over time (ie. Some CO2 scrubbers extend oxygen supply, LiqO2 -> O2 converter, fuel cells, etc.)

**Comment by PhineasFreak** [comment]
OK, so historic parts are out of the question (and no one can have any objection over this, they are set after real life values). Also, you confirmed one of my suspicions, tracking the EC generation/consumption usage gets ugly really quickly.

I was searching some other stuff about electricity requirements, especially for crewed Mars missions, and frequently you come across values like 5 kWh per crew member, so a linear scale with the crew, like the one i assumed, is also not applicable. Another nail in the coffin.

Afterthought No. 1: Even for historic crafts, one could use a base consumption of X Watts and cover the rest using the avionics as a consumer to get the overall EC consumption right. It might turn up that is a worse hack than the generator one though.

Afterthought No. 1: I believe that a TACLS module, like the generic "Life Support Module", could be coded to specify an arbitrary (or real) electricity consumption. That way you can have a specific EC consumer for life support only that won't be locked to any predefined global settings.
