### ISSUE TITLE
RealEngine emissive missing for 1st nozzle per engine

### ISSUE THREAD

**Issue by Temeter** [KSP-RO/RealismOverhaul#1547]
The RealEngine emissive are incomplete in RO, while they work fine in stock KSP. Just so I don't confuse terminology, with emissive I mean the red/white heat shimmer of the engine bell and structure.

This is the emissive in a clean stock install, which works fine: http://i.imgur.com/uboIqND.png

And these are the same engines in a clean RO install: http://i.imgur.com/VEoLQwP.jpg

Basically, in RO all (RealEngine) multi-nozzle engine miss one bells emissive, the single nozzle engines don't have any.

**Comment by PhineasFreak** [comment]
So, RO uses the ModuleEnginesRF module, subclassed from the stock ModuleEngines(FX). This is done via SolverEngines. If the emissives are broken then a suspect would be the [ModuleAnimateEmissive module](https://github.com/KSP-RO/SolverEngines/blob/master/SolverEngines/ModuleAnimateEmissive/ModuleAnimateEmissive.cs).

I may be wildly wrong here though so i will tag the coding pros @blowfishpro, @NathanKell and @Starwaster.

**Comment by Temeter** [comment]
I've only observed the issue with RealEngine's. IE SSTU's RD107 works fine.

**Comment by PhineasFreak** [comment]
These engines are also the only ones that i have ever seen something like that so i am more inclined to say that it is caused by the way these engines are set up **in addition** to the new engine module.

**Comment by Temeter** [comment]
Oh, I don't doubt that, never seen this before.^^

The modder, as skilled as he was, seems to be relatively new to the game. He might have something unusual, which conflicted with RO.

**Comment by Starwaster** [comment]
The source for ModuleAnimateEmissive that was linked to can't compile under KSP 1.2.2 as  it references a member that isn't defined. It also hides inherited members (which isn't necessarily a show stopper but makes me think that I'm not looking at updated code)

So are you using an outdated MAE? Or is it even running properly to begin with? What do your logs say when that assembly is loaded?

Or is there an updated assembly and the code in the repository isn't updated yet?

**Comment by blowfishpro** [comment]
`ModuleAnimateEmissive` does not exist in SolverEngines anymore.  It hasn't for quite some time.  I should probably delete it from the repository.

What animation module do those engines use, and do the RO configs change it?  There are issues with certain animation modules not recognizing more than one `Animation` component.

**Comment by Starwaster** [comment]
I do recall that it wasn't being used at some point. I thought maybe it had been revived again or something.  Removing it would probably be best.

Engines use ModuleAnimateHeat. I don't see it being changed in the RO configs, and I don't see ModuleAnimateEmissive being referenced much in RO except that one config file removes it from several configs and it is present in several craft files where it will produce harmless warning messages when the craft is loaded unless the module is actually somehow present. (such as if someone installed an old copy because they thought it was missing)

So the question still remains as to how MAE is an issue here or IS it actually an issue here? Is someone else's non-RO configs trying to use a deprecated module? @Temeter ?

**Comment by Starwaster** [comment]
Ok so I went poking around in the engine configs for the RealEnginesPack and they are a mess. They don't even use ModuleAnimateHeat and Realism Overhaul doesn't add it to them either that I can see. 

They do use ModuleAnimateThrottle (because... why?). And those don't even look configured properly...

So the problem going on here starts with the base configs

**Comment by Temeter** [comment]
Guess my assumption wasn't wrong, alcentaur added the configuration of these engines with help from the community, without prior experience. Apparently didn't work out that great.

I'd help it, but got no clue how to do anything regarding emissives. If someone wants to help out:

http://forum.kerbalspaceprogram.com/index.php?/topic/154624-122-realenginespack-v11-release-080217/&page=5

> So the question still remains as to how MAE is an issue here or IS it actually an issue here? Is someone else's non-RO configs trying to use a deprecated module?

I've checked it in a completely clean install after notcing the problem in my RSS/RO install.

**Comment by Starwaster** [comment]
Temporarily took this private with a modified config for Temeter to try. That didn't go anywhere. What I think is happening here is linked to RE using multiple FXModuleAnimateThrottle modules. One for each engine bell. And my suspicion is that something is deleting one of those configured modules. Because each bell has a uniquely named emission animation, deleting one of those modules WOULD result in one of the bells to stop emitting.

So I asked Temeter to send me his ModuleManager.ConfigCache. That will reveal the final configured state of the affected engines.

**Comment by Temeter** [comment]
To have it here as well: https://www.file-upload.net/download-12311307/ModuleManager.ConfigCache.html

**Comment by Starwaster** [comment]
Ok so there's several factors at work here. The reason one engine bell (and only one bell) stops glowing is because Real Fuels is replacing FXModuleAnimateThrottle with ModuleAnimateHeat. It assumes that there is only one to replace but Alcentar (RealEngine's creator) is using multiple modules, each one with a uniquely named animation. (so 4 separate animations for 4 bells). That part I'd say is on Alcentar; he should adhere to standard practices that would ensure that his parts don't become incompatible with other mods out there.

But the reason WHY I think it stops glowing at all is because RO reconfigures it with a heat production of 100 which just doesn't seem to get it hot enough to glow. I do notice though that seems to be the case with a lot of engines, so is there something those other engines are doing so that they glow when they heat up? Or should those parts maybe be increasing their heat production?

**Comment by Temeter** [comment]
I'm currently comparing engines and... wow. You're right, the bobcat RD170 and even RO's own E1/H1/LR79 don't glow either. Literally having them burn for minutes on the launchpad, and I can't make out the slightest tint.

That's... really weird. From the past, I remember RO sometimes having engines that took a while to start glowing, but I remember seeing said emissives on hot engines. Something has to have changed. (my install has RealHeat/FAR/DRE)

**Comment by blowfishpro** [comment]
I don't really know about the decisions that went into making most engines glow little if at all but it but it might be somewhat intentional - to my knowledge only the radiatively cooled nozzle extensions of some engines actually glow (RL10, Merlin Vacuum, etc)

**Comment by PhineasFreak** [comment]
So, there are many factors to this one! And i was wrong about the coding side...

Anyway, if it is a problem with the amount of heat production then we can short it out easily. I can open a PR to change the values from the default 100 to something higher or back to the original ones.

Also, as @blowfishpro said, there are only so many engines that are not cooled by the propellants. Most of the engines (stock & mod) have this animation appear easily, probably for the extra "bling" factor.

New "rule" for myself: check the heat animations before committing the PR to see if they make sense.

**Comment by Temeter** [comment]
Case in point: I did check the RL-10 and F-1, both regeneratively cooled engines that do in fact start to glow.

It is inconsistent, though. The NK33 doesn't glow, yet it is a regenratively cooled engines (contrasting with the RD 170). Same for H1 and E1. Wikipedia claims all of Rocketdyne's early engines use regenerative cooling.

---------------------------------------------------------------------------------------------

I've talked to Alcentaur about only using a single emissive; but he doesn't know how to set that up (neither do I). Can someone give him a helping hand?

http://forum.kerbalspaceprogram.com/index.php?/topic/154624-122-realenginespack-v11-release-080217/&page=5

**Comment by PhineasFreak** [comment]
The heat production value is an "official unofficial" one: everybody uses it but not because it is a correct one but because it has been there since...ever. I am sure that the low value is a leftover from some early tries to deal with the broken KSP 1.0 heat system (before fixing it for good). Lowering this will lower the possibility of unintentionally blowing things that they should not (serious issue in the early 1.0 ages).

**Comment by Temeter** [comment]
Does _HeatProduction_ even do anything at this point? I've changed the E-1 to 500, and still don't get emissive. Nozzle on pad ist stable around 2965K.

**Comment by PhineasFreak** [comment]
It is parsed by the ModuleEngineConfigs but i cannot see if the actual result (configHeat) is used for something. The internal (chamber) temperature is calculated by the engine solver anyway.

**Comment by Temeter** [comment]
Well, that's outside of my reach and knowledge.^^

No clue why there aren't emissives.

**Comment by Temeter** [comment]
So, to make sure, for my sanity and to see that there isn't some random issue with my supposedly clean install:

Can any of you confirm that no engine - excluding SSTU - shows emissives? Including regeneratively cooled engines (IE RL10). Also the lackchanges by modifying _heatproduction_; you'd imagine something would happen if you set it from 100 to 1000.

In that case it might be a deeper issue with SolverEngine, and someone should call NathanKell.

**Comment by Temeter** [comment]
So, Alcentaur has updated his packs animations. This fixes the additional nozzles using their own, and not solverengines, emissive controls.

Other problems, if there are, are RO related. So no point leaving this open; if someone wants to discuss how emissives in RO should work, then it deserves its own thread.
