### ISSUE TITLE
1.2 Stock Antenna System vs Remote Tech

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RealismOverhaul#1577]
@alimoncul has been nice enough to bring the current information about these two systems of communication/control/science transmission into one place:
https://docs.google.com/spreadsheets/d/1Kz2IqnK3XANaxrf96aPNxieEAyaJdGX49MpFgcnFIqA/edit#gid=0

I don't use RemoteTech myself, and haven't enabled the stock control system yet either. So, I'll looking for the help of someone who has used RemoteTech.

What changes would we need to make to the RO configs for antennas to work as similarly to Remote Tech when using the stock antenna system without it? At first blush, it appears that we'd want to bump down the  power consumption rates (unless the RO configs already do this, IIRC Alim compiled this info with stock?)

Anything else? does transmitting data take up EC with RT? does the stock behaviour of that need adjusting to match?

@SirKeplan @NathanKell

**Comment by PhineasFreak** [comment]
One major difference between CommNet and RT is the power consumption: with CommNet you only consume electricity when transmitting data but with RT you have both a standby consumption and a transmittion one. And there is not a way to backport this to the CommNet.

You could try to increase the electricity required for a given data size but you would end having 0 consumption when not transmitting and a huge one when transmitting.

For the ProbesPlus pack i am currently adding together the standby and the transmittion power requirements from RT for use under the CommNet system: https://github.com/PhineasFreak/RealismOverhaul/blob/2147415d5c3cda01319c24e314481ca884b17174/GameData/RealismOverhaul/RO_SuggestedMods/CoatlAerospace/RO_CA_ProbesPlus_Antenna.cfg#L47-L55

**Comment by stratochief66** [comment]
@PhineasFreak we have given crew parts 'negative generators' that consume power, so I imagine a similar thing could be done for antennas if we wanted to give them background power consumption.

**Comment by PhineasFreak** [comment]
Oh, also, the effective range calculation. CommNet uses:

```
Range = SQRT (AntennaRange * StationRange)
```

while RT uses:

```
Range = AntennaRange + SQRT(AntennaRange * StationRange)
```

so the values will need to be recalculated for the CommNet system (something that i also need to do for the ProbesPlus...)

We also need to see what RT 2.0 will have, since everything will move under the "CommNet umbrella" (might also use the same rule for the range calculations).

**Comment by smartdummies** [comment]
I would be quite willing to go through the configs and make sure that the antenna power for ComNet for all the antennas. Just need the StationRange values so I can get the correct values

**Comment by PhineasFreak** [comment]
@smartdummies They are supplied by RSS: https://github.com/KSP-RO/RealSolarSystem/blob/master/GameData/RealSolarSystem/DSN_Ranges.cfg#L21

**Comment by NathanKell** [comment]
If memory serves most stuff in ModuleDataTransmitter is virtual so you could subclass it and add the constant drain fairly simply, I think.

Is there any news about nuRT? Haven't heard anything in a while (also wouldn't it be 3.0, since the current one is 2?)

**Comment by PhineasFreak** [comment]
**TaxiService** (one of the RT team members) is working on **CommNet Constellation** (the testbed for the next RT overhaul - currently missing the signal delay and the flight computer features compared to RT) and it is shaping up nicely (a ton of QoL thingies, plus frequencies!).

RT itself has not been given enough love lately (mostly bug fixing) so i imagine that any major update/overhaul will take time.

**Comment by NathanKell** [comment]
Cool! Someone in #RO just linked me to that and it looks cool, and I noticed it was from an RT dev. We definitely put frequencies in with RT-like stuff in mind. :)

Just asked how things are on the RT slack so we'll see if it's alive enough for responses :D

If Constellation has cone angles, it might be worth switching over to it right now and then waiting for more stuff to be added. In practice since MJ doesn't respect signal delay (and signal delay is a GIANT pain anyway) and it doesn't respect occlusion either (and neither does RCS/throttle) we don't lose that much.

**Comment by PhineasFreak** [comment]
Hmm, i will have to double check for the last point, since CommNet does not implement/care about dish cones. Give me two minutes.

**Comment by smartdummies** [comment]
I've been working on the configs and have questions on balancing for RP-0. A great example is the HG-55 Mariner antenna. The current config us to have the RT range of 340Gm at L2 DSN so that it can reach Venus at opposition at expected purchase time. This means that in RO it can reach to Saturn at opposition making it very OP. My instinct is to have RO set the ranges so that the range is identical at L3 DSN and have RP-0 do the balancing act for career mode. @NathanKell perhaps the increases in the DSN ranges should be tweaked. A 10 fold increase in range at L2 make sense as the implementation of the DSN but  the increase at L3 should be lower to represent gains in signal processing. Let me know the path to take and I will make all the updates accordingly.

**Comment by smartdummies** [comment]
I've been compiling a list of antennas in the game and have some proposed setting for the Comm Net values. I have my current list at on [Google Docs](https://docs.google.com/spreadsheets/d/1_VxypG4JDCdGNsH7AGVb23ZL53xCQnoa00iyGjrjTWo/edit#gid=268488052) for a quick review before I start going in and making the config changes. I've gone through stock, AIES, Coatl, RN probes, and Black Leg so far and I will be continuing to build this list as I hit the other supported mods to get all antennas in one place. I am thinking that a branch needs created to put the changes in for testing before merging into master. Review and thoughts?

**Comment by pap1723** [comment]
@smartdummies I requested to be able to view the spreadsheet.

**Comment by smartdummies** [comment]
@pap1723 you should be able to access it now
