### ISSUE TITLE
1kN Thruster has no fuel bars

### ISSUE THREAD

**Issue by Bornholio** [KSP-RO/RealismOverhaul#1681]
[img]http://i.imgur.com/bwmpZDb.png[/img]
Tested several beginning fuel configurations.

**Comment by PhineasFreak** [comment]
IIRC they do not have propellant indicators because they do not actually work as engines but as linear RCS thrusters (uses the same patching conventions from the RO_RCS config file).

**Comment by NathanKell** [comment]
They get the propellant and thrust configs from the RCS global configs, but are still engines (this is because ModuleEngines and ModuleRCS take the same PROPELLANT nodes now, and ModuleEngineConfigs is smart enough to know which it's dealing with) but we can totally add DrawGauge = True (or whatever it is) after the engine config. Or, actually, hmm, there should be no harm in putting it in the RCS globals anyway, since the RCS module would just safely ignore it (or use it, which would also be awesome).

**Comment by PhineasFreak** [comment]
I found an old "issue" (discussion) that i had opened exactly about this feature: https://github.com/KSP-RO/RealismOverhaul/issues/1275

**Comment by Bornholio** [comment]
I'm of the opinion if it is an easy global it would have no harm.  Plenty of use of RCS as engine in small sats. 
@PhineasFreak if the old issue is same context and completes discussion of the issue feel i can close.
Sorry about not seeing that because I search 1kn in title only I guess.

**Comment by PhineasFreak** [comment]
No, it is fine! Would you like to create a PR and add this feature? It is relatively easy and painless.

**Comment by Bornholio** [comment]
Sure will, I'll also make the modified RO engine config.

**Comment by PhineasFreak** [comment]
No limitations apply. Either the mainline RO or the Pap one will do the job. I imagine that the mainline will be faster to merge though.

**Comment by Bornholio** [comment]
looks like the solution if wanted is to add "DrawGauge = True" to the mono-propellant section of RO_RCS_Config.cfg  https://www.dropbox.com/s/dxclj4d0288mqwz/RO_RCS_Config.cfg?dl=0
This does not add a gauge to the RCS stage icons of all the RCS units I had in career.
1kn Thruster: http://imgur.com/9sCCLB4
RCS blocks: http://imgur.com/4v4VHHz

**Comment by PhineasFreak** [comment]
(Un?)fortunately, the ModuleRCS does not support the **DrawGauge** field so expect that these parts will not be affected by it.

**Comment by Bornholio** [comment]
Commit in and merged.
