### ISSUE TITLE
Broken 2 kN thruster in DEV BRANCH

### ISSUE THREAD

**Issue by wb99999999** [KSP-RO/RealismOverhaul#1769]
Some changes seems to have broken most of the configs for the generic 2kN thruster and caused incorrect or no thrust. Awaiting further investigation.

**Comment by Bornholio** [comment]
also add 1kn Thrusters showing low thrust in engine config UI and unknown thrust in VAB part display

**Comment by sgrif** [comment]
The 1kn thruster seems way heavier than it should be, as well (70kg instead of 15kg). Likely the same cause (possibly https://github.com/KSP-RO/RealismOverhaul/commit/d97a1dab4a13230e02806746a60fa5f29b4b5288#diff-52a3305ac0b3fa2a1b798703f5b7439b?)

**Comment by DocRockwell** [comment]
Hey guys,  all the generic thrusters (0.5, 1, and 2 kN) have bugged masses, that are ~500% what they should be (2 kN weighs more than most upper stage engines).

Here is a dirty little patch I made to fix it.

@PART[ca_jib]:FINAL
{
	@MODULE[ModuleEngineConfigs]
	{
		@origMass = .008
	}
}

@PART[microEngine]:FINAL
{
	@MODULE[ModuleEngineConfigs]
	{
		@origMass = .016
	}
}

@PART[RO-2kN-Thruster]:FINAL
{
	@MODULE[ModuleEngineConfigs]
	{
		@origMass = .032
	}
}

**Comment by PhineasFreak** [comment]
The mass issues for both thrusters stem from the **useRCSMass = True** parameter:

https://github.com/KSP-RO/RealismOverhaul/blob/dev/GameData/RealismOverhaul/RO_SuggestedMods/Squad/RO_Squad_Engines.cfg#L945

https://github.com/KSP-RO/RealismOverhaul/blob/dev/GameData/RealismOverhaul/RO_SuggestedMods/Squad/RO_Squad_Engines.cfg#L1010

As a temporary workaround, if you set them to **False* then they will have the stated mass value. But, since the previous version of the global RCS configs allowed these parts to change mass, we will have to check how the **origMass** parameter is calculated in the **RO-RCS** pass.

**Comment by sgrif** [comment]
https://github.com/KSP-RO/RealismOverhaul/blob/dev/GameData/RealismOverhaul/RO_SuggestedMods/RO_RCS_Config.cfg#L85 seems pretty clearly the root cause. Why are we assuming every RCS thruster has 4 more nozzles than it actually does?

**Comment by PhineasFreak** [comment]
Still, it does not add up. With a starting **origMass = 15 Kg** you will have

* origMass = **0.125 * 15 = 1.875 Kg**
* nozzleCount = **4 + 1 = 5**
* origMass = **5 * 1.875 Kg = 9.375 Kg**

since the global RCS config does not define different **massMult** values for the differing propellant options.

**Comment by sgrif** [comment]
There's clearly something going on. Deleting the `nozzleCount += 4` line gives everything the correct mass.

**Comment by raidernick** [comment]
@PhineasFreak @Bornholio @wb99999999 what's up with this, is it still an issue that needs to be fixed before release?

**Comment by PhineasFreak** [comment]
Yes, it is still broken. Removing the **nozzleCount** line, as @sgrif noted, does fix the extra mass. I also did not notice any adverse effects on the general purpose RCS parts (starting mass is correct, increasing tech reduces the mass etc).

**Comment by raidernick** [comment]
fixed here: https://github.com/KSP-RO/RealismOverhaul/pull/1842

**Comment by MikeOnTea** [comment]
The fix here seems to break more than it fixes. Now, all RCS thrusters have the mass (nozzlecount / 8) * mass of the base/reference quad rcs block of their thrust. Except quad rcs that don't specify their nozzlecount because they assume 4 nozzles is the default, they get their correct mass of the reference/base quad rcs, thus quad RCS are now as heavy as 8-nozzle-thrusters.

I also think i know what the original code tried to do: With the original code, a quad rcs was only 8/5 the weight of a single nozzle attitude thruster to represent mass savings because not all mass is in the nozzles.

So to fix this issue, we should really discuss what kind of mass scaling we want:
Should a 2 nozzle thruster have double the mass of a single nozzle thruster, or should we assume mass savings because they share a base and a case etc?

In the latter case, and if we assume that a thruster with twice the thrust has twice the mass, the original code worked fine as it seems, just that the mass of all rcs and the mass penalty of a single nozzle thruster was a little high, leading to the 1kn thruster's weight of 70kg - it just needs some rebalancing to get the weights lower.

Thoughts?
