### ISSUE TITLE
Configs for SXT/Bluedog X405s don't match

### ISSUE THREAD

**Issue by aw1621107** [KSP-RO/RealismOverhaul#1783]
Part names SXTX405 and bluedog.vanguardEngine.

The former has two engine modules, both of which use kerolox + HTP. The Bluedog version has 3 engine modules, one using stock LF/O, one using kerolox, and one using kerolox + HTP.

**Comment by aw1621107** [comment]
I think the reason the Bluedog version has 3 engine modules is that the RO config adds another engine module for the turbopump exhaust instead of editing the existing turbopump exhaust module. Fixing this results in both the SXT and Bluedog engines having two engine configs (one main + one exhaust), but the Bluedog exhaust config still doesn't consume HTP

**Comment by PhineasFreak** [comment]
You have to manually patch the engine in hand in order to get the turbopump exhaust functionality (if supported by the part model):

https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/SXT/RO_SXT_Engines.cfg#L382-L513

The global engine config blindly patches every available engine module but does not insert new engine modules:

https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/Engine_Configs/X405_Config.cfg#L30-L47

If you are getting an engine that consumes LFO (probably the turbopump one) then you have to make an AFTER[] MM pass for that specific module.

**Comment by aw1621107** [comment]
The added engine module comes from the Bluedog RO engine config, not the global config:

https://github.com/KSP-RO/RealismOverhaul/blob/4c30ed8b074fb52720fd17b5b01f84320d80f352/GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_Vanguard.cfg#L50-L85

I think the problem may have arisen because the Bluedog part already provides a ModuleEngines for its turbopump, and it's not being replaced/deleted. What I ended up doing (before reading your comment) was changing the first `@MODULE[ModuleEngines*]` to `@MODULE[ModuleEngines*]:HAS[#thrustVectorTransformName[thrustTransform]]`, and changing the new module to `@MODULE[ModuleEngines*]:HAS[#thrustVectorTransformName[vernierTransform]]`. This appeared to take care of the LFO engine, although it seems that this isn't the best way? Is the AFTER pass you're suggesting supposed to be for deleting the ModuleEngines that uses LFO?

Fixing the missing HTP was just a matter of adding the appropriate `PROPELLANT` node to the Bluedog config.

I'll make a PR once this has been sorted out.

**Comment by PhineasFreak** [comment]
No, that way is currently the one used for every engine part that has multiple ModuleEngines defined in their part config. The **AFTER[RealismOverhaulEngines]** pass is used because:

* The global engine config patches all available engines.
* Any changes done before the **RealismOverhaulEngines** pass (like in the default **RealismOverhaul** pass) will be overwitten by the global engine config.

With this pass you are not deleting the extra engine modules but patching it's parameters, exactly like the "normal" RO engine patches do but in a more "custom" way.

You also guessed correctly that the engine module patching will require a **:HAS[#thrustVectorTransformName[]** check!

So:

* Convert the engine module in your post from a "standalone" module into an **AFTER[RealismOverhaulEngines]** patch for the existing turbopump module.
* Add **:HAS[#thrustVectorTransformName[]** checks for both engine modules.
* ???
* Profit!

**Comment by aw1621107** [comment]
Alright, created a PR

**Comment by aw1621107** [comment]
Fixed by #1792, I think
