### ISSUE TITLE
FASA/RN Baby Sergeant stats don't match

### ISSUE THREAD

**Issue by aw1621107** [KSP-RO/RealismOverhaul#1784]
For example, the FASA 1x motor costs 30.23 funds, has atmospheric ISP of 200, vacuum ISP of 220, while the RN 1x motor costs 5.23 funds, an atmospheric ISP of 214, and vacuum thrust of 235. The 3x/11x motors have the same ISP, but the RN versions are much, much cheaper (180.70 vs 12.70 for the 3x, and 332.58 vs 42.58 for the 11x).

The RN Sergeants also seem to be missing TF configs and alternate engine upgrade configs.

**Comment by raidernick** [comment]
that's because mine are meant to be used on the juno ii only and only one variant was used on that. As for the stats differing the fasa configs are much older and for mine I took the values specifically from the juno ii pages for them. I don't know where the fasa info came from.

As for pricing related stuff I can't help there I don't do career.

**Comment by aw1621107** [comment]
Oh, interesting. I thought that RO did some kind of magic behind the scenes to give different parts representing the same real-life thing the same configs/stats/everything.

**Comment by raidernick** [comment]
this should be resolved per the explanation
