### ISSUE TITLE
RealScaleBoosters Common Centaur Upper no longer has avionics

### ISSUE THREAD

**Issue by lamont-granquist** [KSP-RO/RealismOverhaul#1810]
In 1.2.2-era this part had avionics that would let it fly e.g. the Atlas V HLV to orbit without additional avionics in the payload.

In 1.3.1+spreadsheet+RO-dev this part now only has an uncontrollable science core.  Would need to add ~1000t of avionics in the payload to support the centaur + the boosters at launch which is certainly not right.

It is unclear to me what changed.  Not familiar enough with how avionics works to know how to fix.

Part is here:  https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/RealScaleBoosters/RO_RSB_Atlas.cfg#L342-L487

**Comment by PhineasFreak** [comment]
I do not think that RSB ever got RP-0 integration apart from the engines. Searching the RP-0 repository does not yield any results. Maybe there was another part that included the required avionics?

In any case, Centaur should have approximately 60 t of avionics capacity (~30 for the propellant load plus ~30 for the max payload). The rest should be covered by the core and the boosters (since for single stick variants this capability is around 560 t - a 551 variant with a full 29.5 t payload mass is around 590 t at liftoff).

Pinging @pap1723.

**Comment by lamont-granquist** [comment]
So in 1.2.2/RP-0 i can take the Atlas V HLV and start disassembling it in the VAB and the part that it seems has all the avionics is the Common Centaur.

It would make sense to give the boosters enough avionics for themselves and the centaur enough avionics for itself, but it didn't seem to be the way it was done in 1.2.2 (I don't see where or how it is winding up with any avionics though it doesn't have the usual "supports rockets up to XXXt" module on the part in the VAB).

And the RD-180s also lack TF configs, and I'm sure they need RP-1 pricing and tooling and all kinds of stuff.  But getting the avionics back in them would get them flying again in sandbox.

**Comment by PhineasFreak** [comment]
You could temporarily add support for it by ORing the part name in the stock Centaur avionics node: https://github.com/KSP-RO/RP-0/blob/Developmental/GameData/RP-0/Avionics.cfg#L420-L432. I'll also make a PR to add avionics support for the CCB and Centaur parts.

There is an open PR that adds TF support for the RD-180 (https://github.com/KSP-RO/RealismOverhaul/pull/1733). The engine is already placed and priced in the correct tech tree node so that is the last thing that it is missing. For the tankages, i believe that it is possible to interpolate the prices by both similar tankages from other mods, the PP tooling costs and via the ULA RocketBuilder page.

**Comment by lamont-granquist** [comment]
Ah cool, now that I've got a pointer to that and an example I can at least putter around and make PRs...

**Comment by ctiberious** [comment]
Just an FYI, the Atlas V common core has no avionics.  The avionics are all controlled from the Common Centaur.  The same as how the Delta Cryogenic Second Stage handles all the avionics for the Delta IV.

**Comment by PhineasFreak** [comment]
[The Atlas V Payload Planner's Guide](http://spacecraft.ssl.umd.edu/design_lib/Atlas5.pl.guide.pdf) says otherwise though (page 14):

```
Avionics: Flight Control, Flight Termination, Telemetry
```

Granted, the Flight Termination and Telemetry points are already handled by RT and RP-0 but why also include Flight Control?

Also, considering it from a game-play standpoint, i do not think that having a ~25 ton stage control a >500 ton rocket would be something balanced (similarly, the Centaur-T variant from FASA does not supply avionics for the complete Titan IV launch vehicle. The FASA Atlas (S)LV-3C and Atlas II boosters also supply avionics for their Centaur stages).

**Comment by ctiberious** [comment]
Guidance is handled "From Upper Stage".  Admittedly, "avionics" is really more than just guidance but for our purposes its one of the primary ones.  Though I suppose you could break things up.  Give the Altas V it's own avionics but with minimum (or better yet, no) SAS and give the Common Centaur a powerful SAS.

Honestly, I don't see the issue allowing a ~25t stage control a >500t rocket.  The mass of the stage isn't really relevant in the Atlas V era.  It's really just the "brain" that is on the upper stage.

And the Centaur-T really isn't a good example.  It's true that in older launch vehicles (Atlas D through Atlas III, Titan II, III & IV, even Delta through Delta II), guidance for the launch vehicle and guidance for the upper stage were two separate things.  But my understanding is that the Common Centaur (used on Atlas V) and the DCSS (used on Delta III & IV) moved away from separate guidance to a single, integrated guidance system located solely on the upper stage.

If you do want to separate guidance from flight control (which, again, I suppose is the difference between SAS and Avionics) then don't forget to include comms everywhere that you put Avionics unless you're assuming the upper stage handles all comms.

**Comment by raidernick** [comment]
If this is still an issue please remake it in the correct github this is not an RO issue but an RP0 one. Closing this as it is not relevant to this mod.
