### ISSUE TITLE
Remove stale branches

### ISSUE THREAD

**Issue by raidernick** [KSP-RO/RealismOverhaul#1856]
@PhineasFreak do you think it would be a good idea to finally delete those dead branches. They are from old updates and have all been merged years ago into master. It can just confuse people and cause them to make bad PRs off of them like docrockwell did.

**Comment by PhineasFreak** [comment]
If you can then do so. Most of them are not even applicable anymore, like **EGC_KSP11** and **KSP12Update** and the **e1_engine** has been merged into master.

I'd keep the **Pap-BDB-Updates** and the **smart_parts** since they are still relevant (the smart parts one could probably be merged since RP-0 also had support for these parts - https://github.com/KSP-RO/RP-0/issues/862)

**Comment by raidernick** [comment]
ok @PhineasFreak I removed all the stale branches except those two. I made a pr for the smart parts one and talked to @pap1723 about the bdb one. He said it can't be merged because of all the changes to bdb and needs to be redone. He wants it kept for now as a backup until he redoes it.

**Comment by PhineasFreak** [comment]
Perfect!
