### ISSUE TITLE
Discrepancy in the BE-4 config.

### ISSUE THREAD

**Issue by dearmoon9** [KSP-RO/RealismOverhaul#1886]
Isp is set to 305-341 s here: https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/Engine_Configs/BE4_Config.cfg

But here: https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/VSR/RO_VSR_Engines.cfg it is set to 318-354s.

**Comment by PhineasFreak** [comment]
It does not matter what the values in the VSR part is, the ModuleEnginesRF parameters are always overriden by the ModuleEngineConfigs. The VSR Isp stats are older than the ones BE-4 global engine config (seems that i never updated them).

Speaking about the BE-4, do we have any newer sources about the engine stats? BO had yet to test fire it since the last time that the configs were updated.

**Comment by Capkirk123** [comment]
The BE-4 engineConfig currently agrees with the (still extremely scarce) data on the BE-4, and the engineConfig will overwrite any other values. This issue should be resolved.

**Comment by DRVeyl** [comment]
Closing.  I will do a VSR patch pass soon.  Will clean up old references that end up duplicative of [or worse, contradictory to] global engine configs.
