### ISSUE TITLE
Aerobee engines mass/TWR seems too good to be true

### ISSUE THREAD

**Issue by leudaimon** [KSP-RO/RealismOverhaul#1955]
https://github.com/KSP-RO/RealismOverhaul/blob/3b7167693b13ff325e4c6536d69611181f73ca2a/GameData/RealismOverhaul/Engine_Configs/Aerobee_Config.cfg#L13
I couldn't find any sources for the mass of these engines, but the current values seem off. 
I have no idea how that never came to my attention, but TWR of these engines is 97, 135 and 180 for the WAC, XASR-1 and AJ-27 respectively in the current config. 
This would be crazy good for a modern engine, and impossible for a Post War one. If no source for the mass is available, I was thinking about applying the AJ10-37 TWR to all of them, as that one seems realistic (TWR = 41) and it would be easy to adjust the mass based on the respective thrusts.

**Comment by pianojosh** [comment]
This is a good point, WACs in-game vastly outperform real world missions.

That being said, given how tight funds can be early-game, it might be necessary to completely reevaluate early sounding rocket contract requirements and/or rewards with this change.

**Comment by leudaimon** [comment]
I'm not sure this would have such a big effect in the early career. I made a test with the following changes:
* Instead of the uniform TWR I suggested above, I made it so that the engines kept the same mass relationship among them as the current config does (1, 1.3, 1.5 massMult for the 3 engines in order)
* I gave the XASR-1 the same TWR as the AJ-37. My thought is that as the AJ-37 has gimbaling and these engines don't, it could be possible for the AJ-27 to have better TWR than the AJ-37
* I achieved this by making the standard mass of the part = 0.027kg and all else equal

I then built a WAC-Corporal, under non-optimal conditions:
* 0.3m diameter
* empty (fairly large) nose cone with Tank-I HP type
* main body also Tank-I HP with 80% utilization
* 55s burn time
* dry mass of the whole rocket was 136kg

This rocket was able to break the Karmán line, even though it couldn't get to in-game space for science.

I think this seems reasonable and shouldn't hurt the early career. It may actually make it more challenging to get the space science early, which might be interesting.

**Comment by NathanKell** [comment]
Well, that's a screwup on my part. :)
I'm not sure I ever had a mass value for them, so I might have just invented the 8kg value--I think there was maybe a comment to that effect at one point. The only concern I would have here is aerodynamic stability of (newb-) created WACs, making the tail heavier could lead to issues.

**Comment by leudaimon** [comment]
@NathanKell I couldn't find any sources for the mass. @Bornholio  was trying to figure out the mass from photos of the engine, but I have no idea how to do that. Still 8kg seems very very low... and 12kg for the AJ10-27 even more so. 
The WAC-Corporal I described above has very small fins and worked very well, aerodynamically stable all the way without spin-stabilization. I think even with 27kg, it is still light enough considering the tank mass to not interfere too much with aerodynamic stability, unless you have fairings instead of a nose cone, as fairings always raise the center of lift a lot.

**Comment by Bornholio** [comment]
I come up with a Guess(tm)  of 3.0kg Chamber and nozzle shell, 6mm(1/4")t.  2.1kg for diffusers and 1.8kg for peices, 1.25kg for fittings and pipes.  appears that the piping is 1/4" Flare, probably all stainless steel tube.  If it gimbals i'm guessing we are 2-3kg Short. Otherwise 8kg isn't a bad guess. has anyone seen what chamber pressure is. could make closer estimates as to helium pressure and thus gimbal weight with that.  Looks like the thing we are missing is a high pressurant weight.  that would be part of Tank I.

**Comment by leudaimon** [comment]
These engines do not gimbal... it just feels very wrong that they have several times higher TWR than anything from the same time. How is that possible? 
Anyway... I guess if the only guess we can make is in the same ballpark of the current values, this becomes a non-issue until some real figures for the mass of these engines are available.

**Comment by Bornholio** [comment]
Okay reading oral accounts from some of the original guys on the bumper program over the last week.
One thing i'm missing is a soft soldered plate in the nozzle, this kept the engine at atmospheric pressure during start.  Its 1-1.5kg at most though.  Other things to consider is that the fuel system valves are considered part of the aerobee avionics  Five electrically/pressure and vacuum actuators for ignition, chamber sense and shutoff are included in that. part that on A later AJ engine would be down in the engine proper and covered by a barrier shield.  I think your missing mass is actually in the rather heavy weight of the SR Core. Each of these actuators would be .75-1kg plus tank plumbing (that should be in tank I).    https://web.archive.org/web/20120303082413/http://www.boeing.com/history/mdc/wac.html
WIth this my Care-o-meter is depleted.  there is a small chance that AJ has historical documents that could clear it up.  Otherwise its such a stupid simple engine that I can't see any other avenue to add weight.  The thing that is complex is the nasty fuel.

**Comment by pap1723** [comment]
I confirmed some of the mass values that we are using, but actual mass values on the engine (other than a mention of 12 pounds for WAC-B) is not easy to find.

**Comment by siimav** [comment]
From @lpgagnon on the Discord:
> the basic flaw with letting some of the engine mass be included in the telemetry core is that it falls apart when you add more engines without adding more cores

I'm also in favor of including the mass of the valves in the engine itself.

**Comment by MikeOnTea** [comment]
Same here. As we're currently creating a procedural science core which doesn't have any valves or valve actuators, i guess moving the masses to the engine is the sanest solution?

**Comment by DRVeyl** [comment]
I think you have to.  You can't mandate that an aerobee core be used with this engine.  You can't prohibit additional aerobee engines to be used in a design, or require additional aerobee cores to go with them.  You can't assign the weight of aerobee valves/actuators to every avionics core.

**Comment by leudaimon** [comment]
The thing is... how much are we modelling avionics as exactly these kinds of systems in the first place? My understand has been that avionics mass involves more than electronics, right? The point a raised in the first post here still holds though: the TWR in these engines is better than most more modern engines, which feels very off.

**Comment by Capkirk123** [comment]
I feel like we should probably disregard the reported mass of the aerobee (since it clearly doesn't include a lot of valves and plumbing that we consider part of the engine) base its TWR off of the AJ10 early instead. The AJ10 early does have a bigger nozzle, but its also made of Aluminum (or at least some versions were) and runs at a higher pressure than the aerobee, so it might even balance out.
