### ISSUE TITLE
Mark1Cockpit is burny on re-entry

### ISSUE THREAD

**Issue by ec429** [KSP-RO/RealismOverhaul#1973]
Back in 1.2.2 I build a spaceplane using the X-15 cockpit (from tech node Hypersonic Flight), see e.g. http://jttlov.no-ip.org/sle/tlf2/gallery.html for some pictures of it.  When I updated to 1.3.1, it ceased to be able to re-enter, as the cockpit would start generating lots of internal heat as soon as it got warm.  My suspicion is that this was due to some DRE changes (`GameData/DeadlyReentry/DeadlyReentry-Upgrades.cfg`), but I don't know.

It's not clear whether this change was intended, but @NathanKell suggested it wasn't.

**Comment by NathanKell** [comment]
Nothing has changed on the part since September 2017, AFAICT. So we'll have to re-tune it I guess.. Maybe thermo changed.

**Comment by ec429** [comment]
The DRE changes that I think are responsible are https://github.com/Starwaster/DeadlyReentry/commit/fd65072a1a96baa90ff790a4bb230dbd488bffe7, which was waaay back in June 2017.  (It was probably a long while after that before I updated my install and encountered it.)

I'm not 100% sure what that cfg does, but since the upgrade's `techRequired` is `hypersonicFlight`, which is the node in which we unlock the part, it's not clear that it's useful to us.

Also note that there was a fix to those files https://github.com/Starwaster/DeadlyReentry/commit/bf2aad4d0c1549dadf90b71e0efa12540dbd22fd after DRE moved on to 1.4.0.  I haven't yet tested backporting that fix to 1.3.1, but I hope to do so fairly soon.

**Comment by NathanKell** [comment]
There is no evidence of such MODULE in my configcache, despite having the latest DRE. So I presume either DRE has a NEEDS on it now, or RO nukes it. In either case it wouldn't do anything because it's tied to a node that exists only in the stock tech tree, not RP-1's (ours is hypersonicFlightRP0, IIRC).

**Comment by Schnobs** [comment]
Hold on, that rings a bell...

The DRE mechanism completely bypasses the RO patches. It's insidious: in-game you're shown the RO values for max (skin) temp, but behind the scenes the lower values from DRE are used. Cockpit goes poof at temperatures you expect to be safe. It's in effect by default and turned off once you reach a techlevel that doesn't exist in RP-1.

https://github.com/KSP-RO/RealismOverhaul/pull/1876/ was supposed to fix this, was accepted after some struggle (PhineasFreak: "The specific cockpit is definitely not intended for LEO reentries").

The DRE value of 450K is unsafe even for mach 3. @ec429 if you managed to return this thing from LEO, I'd say the DRE thing has been successfully removed.

**Comment by PhineasFreak** [comment]
LEO returns for space-plane parts require at least 1773 K internal / 2673 K external. I agree that:

* 450 K external is for subsonic parts, not even low supersonic, so there is no way that it is going to ever survive a 100 km suborbital flight.
* RO is a mod that does all the things by its own, meaning that none of the patches from other mods should ever exist/apply. But the DRE **part** patches are going to apply anyway so we need a proper way to either enforce our own settings on top of DRE or change DRE to check for RO before it applies them.

(it would also be a nice thing to tag me instead of just mentioning me with a comment of mine that makes me look like the bad guy...)

**Comment by DRVeyl** [comment]
Given some heating changes in the past 3 years [including a somewhat not-physical but intentional no-reentry tag to some parts], can this be closed?
