### ISSUE TITLE
LY-01 Fixed Landing Gear center of mass misplaced

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/RealismOverhaul#1979]
Picture worth a thousand words: https://media.discordapp.net/attachments/319857228905447436/533322044314746880/220200_20190111113104_1.png?width=400&height=225

(meanwhile the LY05's center of mass is way at the top, which is probably also wrong but at least doesn't defy the laws of physics)

**Comment by DRVeyl** [comment]
Fixed with https://github.com/KSP-RO/RealismOverhaul/commit/206fc2d47e88040d9b366ba7e0aff31cd95d863e.  Might use further tweaking but this should be a lot closer.

![image](https://user-images.githubusercontent.com/25906300/87858627-4b126800-c8fd-11ea-91ee-e81c92fa8795.png)
![image](https://user-images.githubusercontent.com/25906300/87858648-6bdabd80-c8fd-11ea-885c-ca24995f0ad2.png)
