### ISSUE TITLE
mK1 pod rcs plumes KSP 1.4.5

### ISSUE THREAD

**Issue by raidernick** [KSP-RO/RealismOverhaul#2003]
The rcs plumes for the mk1 pod are completely broken in 1.4.5. They are MASSIVE, like 400-500 meters long and fire in the wrong direction(left is right and right is left, etc....). I've seen this issue with mod p{arts that weren't updated to use the new ksp rcs module apparently the stock command pod cfgs are breaking the rcs plumes on these pods and need to be fixed.

**Comment by raidernick** [comment]
Image showing the issue: https://i.imgur.com/fYtsVKh.png

**Comment by PhineasFreak** [comment]
Considering how broken the Squad RO patches are since KSP 1.4.0 this is not surpising. They will require a major overhaul to make them compatible with both the the KSP and the VSR part configuration updates.

For the specific part, it is most probably caused by the legacy ModuleRCS: https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/Squad/RO_Squad_Command.cfg#L539-L560

And on another note, this part is now deprecated. Any RO compatibility patches should be ported over to the new Mk 1-3 pod.
