### ISSUE TITLE
RO solar panels

### ISSUE THREAD

**Issue by raidernick** [KSP-RO/RealismOverhaul#2022]
@pap1723 This needs to be removed and put into it's own mod. RO does not depend on kopernicus and kopernicus is only required if you are using RSS, your changes to the dll force users to download kopernicus since it relies on a library in the dll file.

It also breaks all of the craft files and existing action groups(because it loads even without kopernicus). I'd rather not have this as part of the ro.dll, this dll should only contain things absolutely needed by ro, independent of all other mods. This prevents it from ever needing to be updated, in fact I was planning to remove the checker from it as it doesn't do anything.

This panel module is a good idea and should exist, but not as part of the ro.dll or RO at all. It should be it's own mod that is suggested by RO, same as something like saturable reaction wheels, realheat or kscswitcher, rssdatetimeformatter or KJR.

**Comment by PhineasFreak** [comment]
The whole reason why Kopernicus is required is because RO uses the Kopernicus solar array class to create its own solar array module:

https://github.com/KSP-RO/RealismOverhaul/blob/c65d2b28dc33151dc367b8e70c3fd21f37f1c51e/Source/ModuleROSolarPanel.cs#L8

But the reason why the Kopernicus solar array module is for compatibility with multiple star systems (many of them exist for stock KSP, not so many for RSS - Extrasolar would be the only one but the author recently halted all further development):

https://github.com/Kopernicus/Kopernicus/blob/932565997ef7ef4fb8d5f51b986a4349d26c1cf1/src/Kopernicus.Components/KopernicusSolarPanel.cs

In addition, the global solar array MM patch disables this Kopernicus module anyway:

https://github.com/KSP-RO/RealismOverhaul/blob/de9f4ae694fc84b803e3fe0d8a3dc119b49a24e9/GameData/RealismOverhaul/RO_SolarConfig.cfg#L112

In the end, there is no reason why RO should use the Kopernicus solar array module for its "ModuleROSolarPanel" class. Deriving from the stock "ModuleDeployableSolarPanel" would be a much better choice, otherwise the RO assembly would need to be recompiled every time a new Kopernicus version is released and would break any future forward/backwards compatibility (RO could really get rid of the compatibility checker as non of the classes required any maintenance in the last 2 years or so).

**Comment by raidernick** [comment]
@PhineasFreak that's a good point though I do feel it should be it's own mod still and set as recommended rather than depends(on ckan for instance).

**Comment by PhineasFreak** [comment]
Mmm, maybe a "RealSolarPanels" mod? Who is up for it? :wink:

**Comment by raidernick** [comment]
like I said, it's a good idea and if it's separate you can use it with anything, not just kopernicus/rss

**Comment by pap1723** [comment]
The reason it extends the KopernicusSolarPanel is because the Time Efficiency Curve does not work in the stock ModuleDeployableSolarPanel. I will remove it, but then someone needs to talk to @NathanKell about moving his changes out of RO into a different mod.

@PhineasFreak the global config that disables the KopernicusSolarPanel just stops the MM patch inside of Kopernicus from running (as a FINAL btw). We get everything we need from the class by extending it, so we instead replace the stock panel with our own.

But I will remove it and look for alternative options.
