### ISSUE TITLE
RD-107/108 vernors, main engine are separate modules, configs applied inconsistently

### ISSUE THREAD

**Issue by fat-lobyte** [KSP-RO/RealismOverhaul#2048]
The RealEnginesPack version for the RD-107/108 engines and its derivatives features two different engines:
The main engine and the small vernor engines. While this may seem like a good idea at first, there are two main problems with it:

-  The vernors are not upgraded along with the main engine. This means that the mixture ratios will be incorrect. That's especially problematic for the RD-117/RD-118 (11D512P) variants which use Syntine instead of Kerosene, while the vernors on the same part still use Kerosene.
-  The vernors do not respect ullage and ignition rules, and can be restarted arbitrarily.
-  The vernors are not subject to TestFlight failures and continue to run even if the main engine failed

Is there a way to simply drop the separate config for the vernors, add vectoring to the main engines and make only the model act like the vernor engines are moving?

**Comment by PhineasFreak** [comment]
Yep, that is something that currently affects **every engine that has auxiliary engine modules** (like the LR91 turbopumps or the RD-107/108 verniers). There is a plan to migrate everything to use THRUST_TRANSFORM multipliers but not everything implements that fix (IIRC the SXT X-405 engine does).

Attached are the semi-reworked RealEngines patches. **They will not work as-is for RO but it is a starting point for any interested party in order to implement the required fixes for RO itself.**

[RE_RealEngines_Russian.zip](https://github.com/KSP-RO/RealismOverhaul/files/3144101/RE_RealEngines_Russian.zip)

**Comment by DRVeyl** [comment]
My understanding is this is fixed for RealEngines.  I defer to @Capkirk123 on engine configs, but believe this has been resolved generally in the past few years.  Will leave open briefly if anyone has conflicting information.
