### ISSUE TITLE
UA1205 thrust curve madness

### ISSUE THREAD

**Issue by Schnobs** [KSP-RO/RealismOverhaul#2057]
Was once more annoyed by the current thrust curve's long tail, wanted to fix it. Next thought was that if I start messing with thrust curves, I might as well try to get it right. So...

Step 1, finding a thrust curve online:
https://www.alternatewars.com/BBOW/Space_Engines/UA-1205_SRM_Thrust_Curve.gif
(Apparently taken from NTRS 19750004937, "Titan IIIE/Centaur D-1T Systems Summary")

Steps 2 to infinity: draw up something, try it in-game, refine.
My problem now is that I cannot achieve as much thrust over as long a timespan as depicted in the plot, at least not in static test firings. In order to get even close, I have to assume that the original plot shows vacuum thrust. Is that a sane assumption to make? 

And, paging @pap1723: what is "Mike's thrust curve tool" and where can I get it?

**Comment by MikeOnTea** [comment]
Yep, that curve looks broken, we need to redo it. Would indeed be good to know if the depicted thrust is vacuum or sea level.
My tool is available here: https://gist.github.com/MikeOnTea/4f9baaca7a0f0f27bb2e07d05b43f0ce/
You need ruby for it to work, but i can do the curve as well if we find out what's depicted, but i'd guess it is sea level thrust because that probably makes most sense for a SRB. You can also ping me on IRC/discord if you like.

**Comment by Schnobs** [comment]
Ooops, sorry. I've seen Pap mention it once and that was my only hint about it's existence. We've long wished someone would make something just like that... thank you very much for doing it!

![UA1205_thrust](https://user-images.githubusercontent.com/8556997/57606092-74509f00-7568-11e9-99d4-b063461651d5.png)
Black line is a gnuplot (smooth csplines) of the dataset I've been using as input for the script, the dots are measurements taken in-game using the old and new propellant curves. No perfect match, but in this case that's perfectly fine: the original thrust curve was based on "slow burners" that exceeded the specified operation time by a few seconds. Preparing pull request.

**Comment by MikeOnTea** [comment]
Could you also post the input data you used for the script for reference? I'm thinking about collecting them. If you still have the new and real files used for the plot above, i'd like to take a look at them, as well, because i wonder if the smoothing might explain part of the difference we see here. :)
You also managed to break my curve pretty printing. :D

**Comment by Schnobs** [comment]
This is the dataset that creates the black "ua1205_real" curve above:
--start--
-1	1200
0.2	1200
1	1140
1.01	1140.1
12	1200
44	1000
70	900
88	820
97	800
108	760
110	750
112	700
120	180
127	20
128	15
--end--
I've fed it into your script as it was, only adding square brackets and commas.
As for "new" and "old", that's data collected from test firing the booster in-game. I'm using krpc to report current thrust in 1-second intervals.

**Comment by Schnobs** [comment]
As for my original question: If a source doesn't state whether the numbers given are ASL or VAC, it's likely to be VAC. Seems to be industry standard.
