### ISSUE TITLE
R-4D engine has only 1 ignition and no gimbal

### ISSUE THREAD

**Issue by TransparentElemental** [KSP-RO/RealismOverhaul#2245]
IRL it's capable of many thousands restarts and at least Cassini had them gimbaling. In the game for whatever reason it's limited to just 1 ignition and can not gimbal at all.

**Comment by raidernick** [comment]
It definitely should be able to restart infinitely. However, it shouldn't have gimbal added to it. Cassini had custom actuators installed specifically for the engines to help keep the spacecraft properly balanced because of the huygens on the side. These engines are produced and delivered without the ability to gimbal.

**Comment by TransparentElemental** [comment]
Can you confirm infinite restarts on your side? I am definitely limited to just one on all of the three configs.

**Comment by Capkirk123** [comment]
I can confirm that all R-4D configs have only one restart, using the latest version of RO in KSP 1.7.3

**Comment by Capkirk123** [comment]
Issue corrected here: https://github.com/KSP-RO/RealismOverhaul/pull/2314
