### ISSUE TITLE
ISS Unity Size Problem

### ISSUE THREAD

**Issue by WC12366** [KSP-RO/RealismOverhaul#2303]
ISS Unity (Node 1) is so big that you can't use STS to launch it
![image](https://user-images.githubusercontent.com/41188403/84360400-9483df00-abfc-11ea-9b32-928176522ced.png)

**Comment by DRVeyl** [comment]
There is an errant patch in the REWORK folder that was adding an additional +50% scale factor to Unity (and Destiny) ISS parts.  Fixed with https://github.com/KSP-RO/RealismOverhaul/commit/1e7e3e17a995c731767272592e66b2a566b787c3.

Note the original mod has incorrect attachment node orientation for the bottom node for multiple parts.  If the RO team ever goes through these patches more thoroughly and applies similar changes for using rescaleFactor instead of editing the MODEL scale and manually moving attachment nodes, fixing up the orientation (`@node_stack_bottom[4] = -1`) may be necessary throughout because the original mod does not appear maintained.
