### ISSUE TITLE
Véronique Specific Impulse looks wrong

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RealismOverhaul#2503]
@eggrobin suggested [this as a source](http://www.capcomespace.net/dossiers/espace_europeen/espace_francais/veronique_vesta.htm) but it has no real better data either, other than claiming the much saner 189s sea level specific impulse for the R. It seems pretty clear from all sources however that the switch to Turpentine in AGI increased, rather than massively decreased, specific impulse.

**Comment by eggrobin** [comment]
I will try to get my hands on _Du V2 à Véronique : La naissance des fusées françaises_, perhaps it has more data.

**Comment by eggrobin** [comment]
I have been digging through Olivier Huwart, _op. cit._, and have found quite a bit of information relevant to these configurations; TL;DR checklist of recommendations here, see below for details.

## Recommendations.
The following changes should be made to the configurations described in
https://github.com/KSP-RO/RealismOverhaul/blob/c74581bddd2a84a56c5d244e5ee6d2c81a311d02/GameData/RealismOverhaul/Engine_Configs/Veronique_Config.cfg#L6-L66 and implemented below in the same file.
- [ ] There should be either three or four configurations:
  - three-configuration option:
    1. R/N/NA (which could probably plainly be called Véronique, with a reliability of 21% at a rated burn time of 45 s);
    2. AGI;
    3. 61(M).
  - four-configuration option, in which case nothing should be called plainly Véronique lest confusion ensue:
    1. R/N, with a reliability of 10% at a rated burn time of 45 s;
    2. NA, same characteristics as the R/N, but a reliability of 50%;
    3. AGI;
    4. 61(M).
- [ ] The thrust of the R/N, NA, and AGI versions should be equal, at four tonnes; the thrust of the 61 version should be six tonnes.
- [ ] The specific impulse of the AGI and 61 versions should be 5% greater than that of the earlier versions. 
- [ ] The fuel used for ignition should be furfuryl alcohol and nitric acid, not Tonka-250;
- [ ] Only a minuscule amount of nitrogen (or compressed air, I am not sure what it is exactly) should be consumed.
- [ ] An ammonium nitrate solution (maybe model that as water in RF?) is consumed during main engine operation; I don’t know whether we have a known rate, in any case the point is that it is less heavy than the compressed gas would have be to pressurize the engine.
- [ ] An acute accent should be present on the first e in Véronique (while the name might be a reference to Vernon—though I have not found a confirmation of that claim—it clearly is consistently spelled with an accent, like the name, and I don’t think the accent hampers readability for anglophone readers).

## Rationale.
Now we wade into the sea of papers.

### Models.
For this section see Olivier Huwart, _op. cit._, pp. 139–143.

The existing configuration has a concept of a « production » Véronique engine which is clearly meant to be something post R and pre-AGI ; however the engine design does not change between the R (_Réduite_, shortened), N (_Normale_, normal), and NA (_Normale Allongée_, lengthened normal) at the level at which we model things (the injector design changes in the middle of the Ns and again with the NAs, I don’t think we can really get into those weeds).

The distinction seems to be reliability, but the numbers given of 35 successes, 19 failures make so sense (that is more than the total number of flights of R+N+NA, so it would have to encompass the turpentine AGI or 61(M) flights!).
https://github.com/KSP-RO/RealismOverhaul/blob/c74581bddd2a84a56c5d244e5ee6d2c81a311d02/GameData/RealismOverhaul/Engine_Configs/Veronique_Config.cfg#L319-L349

If we must have a split of the pre-turpentine rockets, the one that makes sense is instead pre-NA (several earlier injector designs, all on rockets meant to be prototypes) vs. NA (final injector design until the massive changes in the AGI, actual scientific flights).

The success rate for the R/N engine is then 1/10 at 45 s (from the N flights excluding N1 which failed early owing to an aileron breaking, the R flights on the same engines having an 8/8 engine success rate but flight durations of a few seconds; R1 is a rocket designed to fly 32 s but flying tethered for 6.5 s; counting N10 as a failure as it reached 45 km rather than the target 70 km owing to combustion instabilities).

The success rate for the NA engine is 2/4 at 45 s.

### Characteristics of the AGI vehicle.
The following improvements are given p. 144., for the AGI (_Année Géophysique Internationale_) over the earlier versions R (_Réduite_), N (_Normale_), and NA (_Normale Allongée_):
- the tanks are made with a new steel, PM 35 (from the steelworks of Pompey), lighter and stronger than the F 66 SS heretofore used;
- the thrust remains the same, at 4 tonnes, with a very different engine design;
- turpentine is used, reducing combustion instability, and **improving specific impulse by 5%**;
- the rocket is equipped with a self-destruct mechanism for the first time.

### Characteristics of the 61 and 61M vehicles.
The Véronique 61 has the following improvements (_ibid_. p. 147):
- engine power brought up to 6 tonnes;
- injector redesigned;
- tanks (with increased capacity) now made of lighter NSP 3 steel;
- goal of 315 km altitude for a burn time of 54 s;
- 9.5 m long vs. 7.3 for the NA and AGI.

However the only flights of the 61 are two trials (V-75 and V-76) and one engine failure (V-79, reached 70 km).
The more relevant one is the 61M (_Modifiée_) version, which is longer (11.72 m), with a burn time of 55 s, payload of 100 kg at a target altitude of 325 km, with 18 successes (and probably the altitude record).

### Ignition and pressurization.
Olivier Huwart, _op. cit._, p. 138, cites _ingénieur général_ Jean Corbeau, « l’histoire de la fusée sonde française » Véronique, _Communication au XXVe congrès de l’IAF à Amsterdam_, p. 4., (note I have not been able to trivially find a copy of Corbeau’s paper, but it may be of some interest if we require further technical details, and should be available in some libraries). Below is an extract of the relevant citation as at pertains to the fuels used during ignition.
> Le moteur est mis en marche par l’ouverture télécommandée de la vanne pyrotechnique du générateur à gaz. Les gaz comprimés […] réglés […] à une pression de 33 bars environ […] chassent les liquides contenus dans les trois réservoirs du générateur et les envoient vers la chambre de combustion de ce dernier. L’alcool furfurylique et l’acide nitrique injectés […] s’allument spontanément du fait de leur hypergolicité. Les gaz de combustion produits sont refroidis et leur quantité est augmentée par l’injection à contre-courant d’une **solution de nitrate d’ammonium** […]. **Les gaz ainsi produits pressurisent les réservoirs principaux** à environ 30 bars. La montée en pression des réservoirs fait éclater les membranes qui se trouvent dans les canalisations qui conduisent l’oxydant et le combustible des réservoirs vers le moteur. L’alcool furfurylique, allumeur hypergolique […] s’écoule d’abord à plein débit à travers la chambre de combustion du moteur ; l’arrivée de l’acide nitrique est retardée est dosée par une vanne à ouverture progressive ; ce retard et cette arrivée progressive assurent un démarrage doux du moteur. Après quelques secondes de fonctionnement, l’alcool furfurylique est épuisé et l’alimentation de la chambre se poursuit en kérosène.

Emphasis mine. [Google Translate](https://translate.google.com/?sl=auto&tl=en&text=Le%20moteur%20est%20mis%20en%20marche%20par%20l%E2%80%99ouverture%20te%CC%81le%CC%81commande%CC%81e%20de%20la%20vanne%20pyrotechnique%20du%20ge%CC%81ne%CC%81rateur%20a%CC%80%20gaz.%20Les%20gaz%20comprime%CC%81s%20%5B%E2%80%A6%5D%20re%CC%81gle%CC%81s%20%5B%E2%80%A6%5D%20a%CC%80%20une%20pression%20de%2033%20bars%20environ%20%5B%E2%80%A6%5D%20chassent%20les%20liquides%20contenus%20dans%20les%20trois%20re%CC%81servoirs%20du%20ge%CC%81ne%CC%81rateur%20et%20les%20envoient%20vers%20la%20chambre%20de%20combustion%20de%20ce%20dernier.%20L%E2%80%99alcool%20furfurylique%20et%20l%E2%80%99acide%20nitrique%20injecte%CC%81s%20%5B%E2%80%A6%5D%20s%E2%80%99allument%20spontane%CC%81ment%20du%20fait%20de%20leur%20hypergolicite%CC%81.%20Les%20gaz%20de%20combustion%20produits%20sont%20refroidis%20et%20leur%20quantite%CC%81%20est%20augmente%CC%81e%20par%20l%E2%80%99injection%20a%CC%80%20contre-courant%20d%E2%80%99une%20solution%20de%20nitrate%20d%E2%80%99ammonium%20%5B%E2%80%A6%5D.%20Les%20gaz%20ainsi%20produits%20pressurisent%20les%20re%CC%81servoirs%20principaux%20a%CC%80%20environ%2030%20bars.%20La%20monte%CC%81e%20en%20pression%20des%20re%CC%81servoirs%20fait%20e%CC%81clater%20les%20membranes%20qui%20se%20trouvent%20dans%20les%20canalisations%20qui%20conduisent%20l%E2%80%99oxydant%20et%20le%20combustible%20des%20re%CC%81servoirs%20vers%20le%20moteur.%20L%E2%80%99alcool%20furfurylique%2C%20allumeur%20hypergolique%20%5B%E2%80%A6%5D%20s%E2%80%99e%CC%81coule%20d%E2%80%99abord%20a%CC%80%20plein%20de%CC%81bit%20a%CC%80%20travers%20la%20chambre%20de%20combustion%20du%20moteur%E2%80%AF%3B%20l%E2%80%99arrive%CC%81e%20de%20l%E2%80%99acide%20nitrique%20est%20retarde%CC%81e%20est%20dose%CC%81e%20par%20une%20vanne%20a%CC%80%20ouverture%20progressive%E2%80%AF%3B%20ce%20retard%20et%20cette%20arrive%CC%81e%20progressive%20assurent%20un%20de%CC%81marrage%20doux%20du%20moteur.%20Apre%CC%80s%20quelques%20secondes%20de%20fonctionnement%2C%20l%E2%80%99alcool%20furfurylique%20est%20e%CC%81puise%CC%81%20et%20l%E2%80%99alimentation%20de%20la%20chambre%20se%20poursuit%20en%20ke%CC%81rose%CC%80ne.%0A%0A&op=translate) does a decent job here.

This means that, as in Ariane 4’s Vikings (and PSLV’s Vikas), gas generator exhaust cooled by water (here with some ammonium nitrate in it) is used to pressurize the tanks; contrary to those, the engine is _pressure-fed_, so that the gas generator (fed at 33 bars) serves only to pressurize the main tanks (which feed at 30 bars). The reason for this design is that it is lighter than the pressurant would be (Olivier Huwart, _op. cit._, p. 137).

**Comment by leudaimon** [comment]
On a glance at the TL:DR, instead of having two configs that are different only in reliability, should be better to just use these as a guideline for starting and final reliabilities (still, I don't think it makes sense gameplay-wise to have anything with significantly less reliability than 50%).

**Comment by NathanKell** [comment]
This is _awesome_. Thanks @eggrobin ! <3
I think you are correct @leudaimon that it should just be starting and ending reliability.
