### ISSUE TITLE
latest mod version for 1.10 not compatible with 1.12

### ISSUE THREAD

**Issue by cjeod23** [KSP-RO/RealismOverhaul#2542]
the mod is causing the loading screen to get stuck at "Loading Part Upgrades" I tried to google it and says something to do with DLL or missing version of a mod. Please update

**Comment by Alex6511** [comment]
![image](https://user-images.githubusercontent.com/7919184/140693514-8e1c4533-3ade-4c98-a34b-27b2baa7fe81.png)
![image](https://user-images.githubusercontent.com/7919184/140693543-767c0bb5-0235-41dd-9fd2-cf1ae15fd9fd.png)
![image](https://user-images.githubusercontent.com/7919184/140693551-4c051e92-547f-4672-9fc8-b82b437cfd5b.png)


Yeah uh, that's because it's not supported. As noted in a _few_ locations, only 1.10 is supported.
