### ISSUE TITLE
Potential Wheel config issues

### ISSUE THREAD

**Issue by FittedOrphan68** [KSP-RO/RealismOverhaul#2543]
One config im pretty sure needs updating is the XL3 wheel config [roverWheel3]. The RO update attempts to modify @MODULE[ModuleWheelMotor]. But the stock part uses MODULE[ModuleWheelMotorSteering] for its janky, much to be desired steering system.

The others I have no clue the effect but however noticed that the RO config modifies the overall part mass to below the mass of the MODULE[ModuleWheelBase] on a couple parts:
@PART[roverWheel2|roverWheelM1-F]:FOR[RealismOverhaul] {
    %RSSROConfig = True
    @mass = 0.015
}
//STOCK CONFIG//
	MODULE[ModuleWheelBase] {
		mass = 0.040 	  }

@PART[roverWheel3]:FOR[RealismOverhaul] {
    %RSSROConfig = True
    @mass = 0.75
}
//STOCK CONFIG//	
	MODULE[ModuleWheelBase] {
		mass = 0.8    }

Just thought I'd point them out, and as always, if I'm wrong; Sorry, I'm dumb sometimes!

**Comment by DRVeyl** [comment]
Looks like the `ModuleWheelBase.mass` field is only used to set the mass of the wheelCollider for Unity's physics.  It might make sense for that mass to be less than the part mass, but it certainly doesn't make sense for it to be *more* than the part mass.  I'll adjust patches in RO's Squad parts configs for wheels to set ModuleWheelBase to the overall part mass.

Also thanks for the note on the broken patch for ModuleWheelMotor instead of ModuleWheelMotorSteering.  Will fix.

(A more in-depth look into wheels is not something I'll put on my plate, but if someone else wants to dig into that and provide info or, even better, PR fixes, that'd be great.)
