### ISSUE TITLE
Name title of Bobcat's Mir Core RO Config is wrong

### ISSUE THREAD

**Issue by Sepehr3987** [KSP-RO/RealismOverhaul#2617]
Name Title of the RO Config for Bobcat's Mir Core Module isn't correct.
It is `
	@title = Mir Core Module` instead of `
	@title = Mir Core Module/Zvezda Module`
So when people want to search for Zvezda Module in their VABs, That part isn't show up ingame on their own.
In attached below file, I have edited RO Config That I edited
[RealismOverhaul-v14.10.0.0.zip](https://github.com/KSP-RO/RealismOverhaul/files/8379692/RealismOverhaul-v14.10.0.0.zip)
 I really wanna to Participate KSP-RO, But don't know how; Because I'm going to start writing & editing RO Configs. (Go to Game data/RealismOverhaul/RO_SuggestedMods/BobCat Then you can find the Edited file RO_Mir) **I HAVE KSP 1.11.1 WITH RO, SO I AM USING THE OLD VERSION OF REALISM OVERHAUL; I ALSO DELETED SOME CRAFTS THAT I DON'T WANTED**

**Comment by DRVeyl** [comment]
Best way to contribute would be to fork the repo, change the file that matters, and submit a Pull Request back with the fix.  Next to that, just posting the updated file in here rather than the entirety of the Gamedata folder.

However, this isn't actually the problem.  The part title is not what is searchable in the VAB, the *tags* are.  (This is a field in the part config.)  We can add "Zvezda" to the tags, presumably.

**Comment by Sepehr3987** [comment]
Hello,
Thank you for helping me out for how to contribute; Soon I will fork the repo and then submit another pull request with the edited file attached to it.
