### ISSUE TITLE
ConformalDecals should have PhysicsSignificance = 0

### ISSUE THREAD

**Issue by Gordon-Dry** [KSP-RO/RealismOverhaul#2746]
See
GameData\RealismOverhaul\RO_SuggestedMods\RO-ConformalDecals.cfg

Why?
https://forum.kerbalspaceprogram.com/index.php?/topic/194802-18-112-conformal-decals-0212-decals-done-the-right-way-now-on-ckan/&do=findComment&comment=4203468 and following

**Comment by lpgagnon** [comment]
PhysicsSignificance=1 means "add mass of part to parent". It has nothing to do with FAR, and is probably "correct" for decals.

**Comment by drewcassidy** [comment]
it is redundant however, since the decals already have PhysicalSignificance=NONE

**Comment by Capkirk123** [comment]
In the case of a part having the same parameter defined twice, KSP will use the last instance defined, so `PhysicsSignificance=1` overrides `physicalSignificance=NONE` (assuming KSP even correctly parses the latter, since it incorrectly uses a lowercase p).

Anyway, as mentioned above, `PhysicsSignificance=1` is the intended setting for decals so their mass is added to the parent part.

**Comment by drewcassidy** [comment]
> assuming KSP even correctly parses the latter, since it incorrectly uses a lowercase p).

It's not incorrect. There's two different fields, one with a lower case p that's an enum, and one ol that's upper case that's an int

**Comment by Capkirk123** [comment]
> > assuming KSP even correctly parses the latter, since it incorrectly uses a lowercase p).
> 
> It's not incorrect. There's two different fields, one with a lower case p that's an enum, and one ol that's upper case that's an int

That's horrifying. Well, regardless, this is still intended behavior, and both settings have no bearing on the issue brought up in the original post.
