### ISSUE TITLE
Possible to switch to kjr next?

### ISSUE THREAD

**Issue by falcon470** [KSP-RO/RealismOverhaul#2814]
as the title says is it possible for realism overhaul to switch to kerbal joint refinforcement next? reason why i ask is infernal robitics says it requires it, i am feeling a little adventures so i am gonna try to merge some of the mods and see what happens, btw how intertwined is kjr continued and realism overhaul, if i remove it and put in kjr next what might or might not break?

**Comment by falcon470** [comment]
Little update, i havent tried kjr next, little iffy on removeing a dependency for realism overhaul. However ckan errorosly states that kjr next is a depenency of infernal robotics, checking the page for the mod and it only list it as a recomendation, supposed to work better according to the mod developer espesially for hinges the way the autostrut is done they state is better, but seems to work fine with out, I am sure theres some cavets to this but its better then the one that was meant for realism overhaul in 1.81 i tried that one first, had weird behavior like the right click menu not working in the editor, although every thing seemed to work fine at first, either way I am happy with the results, sorry for going on a tanget what i am trying to do probally wont work with the stock robotic parts...... too wobbly

**Comment by falcon470** [comment]
another update, so it seems like ckan decidees dependincy checking here and on the web page it doesnt list kjr at all so by that, i am not sure what to think other then that i really dont trust ckan any more at least not to tell me what i can do or cant.

**Comment by siimav** [comment]
No, RO is not going to switch. KJRc works fine and has gotten quite a few fixes and improvements recently. For the most part we do not want to let CKAN prompt the user about which variant of a mod to install either because that just creates unnecessary support requests.
CKAN dependencies are only as accurate as the mod author defining them. If you disagree with any of them then take it up with the person maintaining the mod instead of blaming CKAN.
