### ISSUE TITLE
Career Mode Disable

### ISSUE THREAD

**Issue by mspalding75** [KSP-RO/RealismOverhaul#2917]
Hello! Can you please make the dialog box that pops up locking out career mode without RP-1 toggle-able in config or options? I have pretty heavily modded my own game to overcome the limitations of RO for career mode and suddenly not being able to create a new career is a huge problem. I understand the desire to push people towards RP-1 for career mode, but making it impossible to bypass this without downgrading is not a great experience.

**Comment by NathanKell** [comment]
It's less that I want to push people towards RP-1, it's that RO makes a bunch of changes that make the stock career 100% nonfunctional. As I said recently when someone else brought up RP-1-less career:

RO drastically changes a bunch about stock KSP that means a new career mode is needed

* Part capabilities have no relation to their original capabilities, or (if from RO-first mods) may not have techs set at all. So a tech tree is needed.
* Ditto for costs
* KSP career limits from buildings don't work anymore, like size/mass limits, part counts, tracking station comm net stuff, the level 1 and level 2 runways cause issues in RSS so you should only ever have the level 3 visual model, etc
* Contracts are designed for KSP-level dV requirements, so they'll ask you to do insane things like pull an asteroid into Earth orbit, or rescue a craft outside the orbit of the moon, or whatever. And that's not even touching the part-test contracts
* ... and so forth.

If you've managed to solve all those problems (and the others that haven't immediately come to mind--those are the biggies), then sure, I can add some sort of MM-based override for you. Because at least that much is needed, since at the very least you are taking on the RP-1 burden of placing and pricing all (or at least all used!) parts and engine configs (and any other kind of config), since otherwise you're just playing in Sandbox With More Fiddly Bits (i.e. the techs and costs assigned to most RO parts are gibberish).

**Comment by mspaldin75** [comment]
Yeah, if it's not too much to ask I would appreciate having a way to toggle that blocker off. To make a long story short, I've essentially built out a couple hundred parts and set them up with all of the necessary RO modules/tweaks to get them to play nice, but also included tech tree/cost/entry cost stuff to balance them. Then I disabled all of the RO baseline parts so it's basically career mode with all of my custom career-balanced-ish parts and the backend tweaks and QoL stuff that RO integrates powering it all behind the scenes. It's worked out exactly how I was hoping it would, I've gotta commend you on how thorough your commenting is throughout the RO configs because it has made integrating my own parts a million times easier.

**Comment by NathanKell** [comment]
Sure I'll add a MM setting somewhere for you. And glad it was easy to figure out! Hopefully all the parts you've made are on some github repo somewhere? We might want to include them in RO proper! :)

**Comment by NathanKell** [comment]
Add
```
REALISMOVERHAULSETTINGS
{
    allowCareer = true
}
```

somewhere and, when RO next releases, it'll work.

**Comment by Sheepdog2142** [comment]
Did this ever get added?

**Comment by Capkirk123** [comment]
Yes
