### ISSUE TITLE
VSR Solar Panels

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RealismOverhaul#331]
We need to redo our calculations regarding area for these panels, since the area differs from stock models.

**Comment by Kelnor277** [comment]
I could give this a shot.
Are you talking about the RO_Squad_Electrical.cfg file?
It looks like VSR has different rescale factors? So just recalculate the rescale then add a chargeRate to the VSR entry?

If so one question, these entries are from the RO stock panels part solarPanels2:
"%rescaleFactor = 1.2"
"@description = Shielded extendable sun-tracking Level 2 solar panel. 1.5m^2. "
I take it that 1.5m^2 is after rescaling.

So since VSR is scaled at 1.21 for this part:
1.5m^2 / 1.2 = 1.25(to unapply the RO scaling)
Then 1.25m^2 * 1.21=1.573m^2 (to get the VSR scaled size
It's level 2 so 1.573m^2 * 0.126kW/m^2=0.198198
so add:
@MODULE[ModuleDeployableSolarPanel]
	{
		@chargeRate = 0.198198	// Level 2 @ 0.126kW/m^2
	}

to the VSR part entry?

**Comment by NathanKell** [comment]
Ah. Heh, I never actually closed this, oops.
I actually did this some months ago. :)

Sorry about this!
