### ISSUE TITLE
Stock fuel tank sizes

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RealismOverhaul#428]
I am **so** done with hearing "but my tanks don't fit my pods!"

Options.
1. Just ignore it (current policy).
2. Rescale the tanks.
3. Require Proc parts and hide/prune the stock tanks.

Thoughts?

**Comment by JandCandO** [comment]
I like the idea of requiring procedural tanks, it would cause less confusion. Personally, I manually delete the stock tanks whenever I create a new RO install to save on memory and reduce VAB clutter.

**Comment by space-is-hard** [comment]
@JandCandO I'm with you on that, but unfortunately that would necessarily break many user's designs

**Comment by Temeter** [comment]
Please don't do number three. Mods including - from a purely functional standpoint - tend to cause all sorts of issues, especially when they are independently updated and sometimes bugged. And RO/RSS is already very complex and hard to see through.

I'd say list ProcParts under dependencies (and add it to CKan). Don't make it actually necessary, just list it there. Gameplay-wise it is basically required anyway because of pod size, and otherwise it's like 5 parts or so. Imo the best way to do it, found it always a bit weird how it's only listed as recommended.

Optionally rescaling stock parts might make a lot of sense, too. Meaning 1.25m > 2m, 2.5m >4m, 3.75 to 5(?). The tanks are kind of weird in how they don't really fit anything. Might break some craft compatibility, ofc.

**Comment by pap1723** [comment]
We support none of the prefab tanks. They exist, but we will not remove them.
