### ISSUE TITLE
RemoteTech_Settings.cfg collisions.

### ISSUE THREAD

**Issue by LebedevRI** [KSP-RO/RealismOverhaul#568]
Relevant: https://github.com/KSP-CKAN/CKAN-meta/issues/775

Hello.

File `RemoteTech_Settings.cfg` that is in release (e.g. [RealismOverhaul-v10.4.1.zip](https://github.com/KSP-RO/RealismOverhaul/releases/download/v10.4.1/RealismOverhaul-v10.4.1.zip)) is different from [GameData/RealismOverhaul/RemoteTech_Settings.cfg](https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RemoteTech_Settings.cfg)
And apparently it is from *RemoteTech RSS Configuration*.

But *RSS* is not a required mod for *RO*...

I'm not 100% sure, but i think, *RO* either should depend on *RSS*, or not contain `RemoteTech_Settings.cfg` that is designed for *RSS*.
(Or *RSS* version of `RemoteTech_Settings.cfg` should not re-use stock **Mission control** GUID - 5105f5a9-d628-41c6-ad4b-21154e8fc488, to keep then co-installable.)

**Comment by RedAV8R** [comment]
Well. This is why you can't compare current git with previous releases.

What you are catching is a change in thought, and yet to be released items.

A minor change has been done so that the RemoteTech adds ground stations for the real world upon installation of RSS. THEN upon install of RO further changes RemoteTech to real world conditions.

When the new RO is released, the new RSS will be released concurrently. End effect. No change for RO users. Because as you have mentioned RO doesn't require RSS. But now with RO you get real world physics workings (at least those capable of RT)...but ground stations are going to be dependent upon the 'galaxy' one chooses to work with.

Play with a completely fictional solar system with RO. No problem. One does need to create new RT ground stations to work with it though. If the old system was in place as it is currently if you played with RO, no matter what galaxy you play with, you'd get Earth ground stations.

**Comment by LebedevRI** [comment]
>Well. This is why you can't compare current git with previous releases.
>
>What you are catching is a change in thought, and yet to be released items.

Yeah, i did not try to check whether it was already fixed in `git diff v10.4.1..master`

>A minor change has been done so that the RemoteTech adds ground stations for the real world upon installation of RSS. THEN upon install of RO further changes RemoteTech to real world conditions.

Sounds good

>When the new RO is released, the new RSS will be released concurrently. End effect. No change for RO users. Because as you have mentioned RO doesn't require RSS. But now with RO you get real world physics workings (at least those capable of RT)...but ground stations are going to be dependent upon the 'galaxy' one chooses to work with.
>
>Play with a completely fictional solar system with RO. No problem. One does need to create new RT ground stations to work with it though. If the old system was in place as it is currently if you played with RO, no matter what galaxy you play with, you'd get Earth ground stations.

Yes, also sounds good, pretty much what i wanted in the first place.

>You can close this issue.

Thanks for the explanation.
I can only hope that in next release it will indeed work as described :)

**Comment by RedAV8R** [comment]
It'll work :)
