### ISSUE TITLE
Tantares & Tantares LV Tweaks needed

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RealismOverhaul#604]
I'm just leaving some comments on Tantares bits that appear to need some adjustment.

* Phobos-Grunt & Fuji tanks report the same fuel volume, but are substantially different sizes

* Block D upper and lower attachment nodes are within the part. Bottom -1.49751 & Top 1.39751 may do, I moved them to those settings with NodeHelper while testing.

* Proton first stage doesn't have a fuel guage.

* No FX on the 4 vernier engines on the Proton third stage. Are they intended as just ornamental?

* N1: The Block G appears to be 1T too heavy (astronautix reports 6T, is 5+2T in Tantares). This, and other small things may be necessary to allow an N1-Lunar mission to be carrier out.

**Comment by Niemand303** [comment]
>Phobos-Grunt & Fuji tanks report the same fuel volume, but are substantially different sizes
Fuji is somewhat a placeholder since it was only a concept, so I made some realistic (as it seemed to me) numbers (though the size of the craft is close to actual measuring by how it fits the H-II rocket)

>Block D upper and lower attachment nodes are within the part. Bottom -1.49751 & Top 1.39751 may do, I moved them to those settings with NodeHelper while testing.
Thanks! Actually, it's a sizing bug, but looks like that size is closer to reality.

>Proton first stage doesn't have a fuel guage.
Yep, it's weird and I'm trying to find a reason why it doesn't add them. I will check it again (since this bug persisted since the first version of configs despite any changes in the file).

>No FX on the 4 vernier engines on the Proton third stage. Are they intended as just ornamental?
They were made RCS, so I converted them into RCS module too, but can change that

>N1: The Block G appears to be 1T too heavy (astronautix reports 6T, is 5+2T in Tantares). This, and other small things may be necessary to allow an N1-Lunar mission to be carrier out.
Yep, I guess it's a typo, gonna fix that immediately. I took the LK data from RN configs, so I think that would be correct.

**Comment by stratochief66** [comment]
So, are all of the things I said in here that were actually bugs/fixable done? I just want to confirm in case I can close this issue now. @Niemand303

**Comment by SirKeplan** [comment]
Either the LK crew cabin, or the LK Fuel tank is scaled wrongly,the cabin is too large in relation to the tank/landing frame
