### ISSUE TITLE
Tantares Craft Files

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RealismOverhaul#613]
* Soyuz Early - Is there any way to have the Cyl End a bit higher? Currently, the antenna at the top of the Soyuz is poking out of the fairing. Also, I think all/most of the other craft have launch clamps. I'm not sure if they are entirely necessary to include, but including them and staging them properly can be handy for new players. Also, since you have proper verniers on this craft, could you lock the gimbal of the engines that shouldn't have gimbal on the real craft? The upper stage engine should probably be set up to hot stage (so, engine lights then the next stage decouples) for ullage sake and historicity. Should the Igla antenna be able to pop our, or does that not have an animation? There appear to be 4 RCS looking ports at the base of the Soyuz-T PAO module, do they not function or did I fail? I launched from KSC, so not the right location, but I got into orbit with a lot of dV remaining (~1000 m/s) so some tank masses may be a little light?

**Comment by stratochief66** [comment]
* Vostok - The orbital propulsion module has a plume, but no flare? It looks a bit strange. Same comments about hot-staging and clamps as above.

**Comment by stratochief66** [comment]
Beyond these small comments, the craft are really excellent, and in excellent shape overall. The fuel mixes are great, they look fantastic, and include a number of parts I failed to put on myself when I tried to build these myself.

I look forward to the Proton and N1, if you plan to build those later :)

**Comment by Niemand303** [comment]
>Soyuz Early - Is there any way to have the Cyl End a bit higher? Currently, the antenna at the top of the Soyuz is poking out of the fairing

Look at the photos of early Soyuzes, their fairings had some parts poking out, like docking antennae, periscope etc. It's the closest I could make and it doesn't hamper the ascent.

>The upper stage engine should probably be set up to hot stage (so, engine lights then the next stage decouples) for ullage sake and historicity

Ye, I can do that.

>Should the Igla antenna be able to pop our, or does that not have an animation?

It worked with RT2 when I tried, what happened to it?

>There appear to be 4 RCS looking ports at the base of the Soyuz-T PAO module, do they not function or did I fail?

I should look into that, but those are supposed to be reserve engines (basically working as RCS, maybe I accidentally fed them with HTP instead of UDMH/NTO) 

>I launched from KSC, so not the right location, but I got into orbit with a lot of dV remaining (~1000 m/s) so some tank masses may be a little light?

Well, there is some orbit inclination problem (51 degrees from Baikonur placed at 45 degrees, so not flying directly eastward), and I had to model the R-7 after later modifications with lighter dry mass, otherwise you won't be able to put later Soyuzes in orbit (or that's just my bad piloting)

>Vostok - The orbital propulsion module has a plume, but no flare? It looks a bit strange.

True, I took the effect from RN configs, so I think both can be changed.

>I look forward to the Proton and N1, if you plan to build those later :)

Yep, I plan on building these soon, though some tweaks to N-1 ignitions should be done.
