### ISSUE TITLE
NearFutureTech issues

### ISSUE THREAD

**Issue by danielguo** [KSP-RO/RealismOverhaul#631]
1. In RO_NearFuture_Electrical_Nuclear.cfg, the NFT nuclear generator now uses FissionReactor Module that uses a different format for ElectricCharge generation.
2. In RO_NearFuture_Propulsion_Engines.cfg, the 3 pit engines need additional:
   @MODULE[VariablePowerEngine]
   {
       @ConstantThrust *=0.001
   }

**Comment by stratochief66** [comment]
Anybody interested in NearFuture support in RO could test it out and quantify any issues in this thread.

**Comment by lOmicronl** [comment]
We've recently had a user come to us in the Near Future thread with a support request and, as it turns ut, the engine config is actually so badly outdated that is causes the plugins to throw nullrefs nowadays.

I'd be willing to help out with fixing it, but I'll be honest: my one playthrough with Realism Overhaul was back in .24, and I haven't touched it since because I determined that it simply isn't what I'm looking for in KSP. As a result, I'm fairly clueless as to how RO does things. Just looking at the respective config shows several things I can't identify the purpose of.

So I'll definitely need to do this in cooperation with someone who actually knows how RO works under the hood, and what values the engines (and other stuffs) are supposed to have.

**Comment by jwvanderbeck** [comment]
Can we get a log showing the exceptions?

**Comment by lOmicronl** [comment]
Ah, sorry if that came across wrong, but I meant the Near Future Propulsion plugin is throwing nullrefs when RO is installed.

The only problem RO has in this case are the outdated compatibility configs, which I hope to assist in redoing.

**Comment by jwvanderbeck** [comment]
Right, but the logs can potentially help us figure out what needs to be fixed in the config :)

**Comment by lOmicronl** [comment]
Oh, I know perfectly well what trips it up. :) 

The thing I have no idea about is why the config adds strange fields like "%RSSROConfig = Extrapolated", or a Module called "WarpableEngine". I mean, I can make educated guesses on some of this stuff, but I don't actually know any specifics.

Or why some of the VASIMRs are represented with dual fuel modes and others have one fuel mode deleated. Or why the thrust and Isp values of some of the engines don't match what I can find online about their realworld inspirations, despite this being Realism Overhaul (I can only surmise you guys got better sources than I do). That kind of stuff.

**Comment by lOmicronl** [comment]
I've started some preliminary work on updating the engine config, and the main thing that's currently throwing me off is the big difference in the way the ion thrusters and hall thrusters are treated versus the MPDTs, PITs and VASIMRs (which I'll call theoretical plasma thrusters from now on). You'll clearly see what I mean when you look at how the configs are laid out for those.

My first question is thus: do I need to bother giving the theoretical plasma thrusters detailed stat adjustments, or is there no particular interest among the RO team in this? Since, as you know, the engines are theoretical. And thus the numbers would not have much basis in reality by default. I'm not sure if the original author of this config just didn't get to finish these configs, or if they were intentionally left minimal.

My second question is in regards to the way this config removes Ec as a propellant and instead adds negative alternator values to model power draw. Is that the intended function of electric engines in RO, or is that just a shortcut the original author took?

Because this leads to an issue with the way NF plugins manage power draw themselves. On both the PITs and the VASIMRs, power consumption is specified inside the custom module node, and the plugin specifically overrides the Ec consumption from propellant and replaces it with its own value. However, it will not override an alternator, as it is not designed to function that way; if an alternator is present, the engine will consume power twice. And if neither an alternator nor an Ec propellant is present, the editor info won't have a field that shows how much power the engine draws. Finally, regardless which solution you pick, the display will always be inconsistent with engines that use the alternator method.

My third question is in regards to the DS4G thruster. RO currently uses stats that represent a subscale test model, which matches the current visual appearance of the part. However, at some point (probably along with the KSP v1.2 update), the DS4G will get a new model. In Near Future, the part is supposed to represent the actual flight article, and the new model will reflect this - it will look like a finished engine, and not like a set of metal plates bolted together. Since there is no real flight article, the new model unlikely to actually have an IRL counterpart.

This raises the question what you want the part to represent in RO. Continue to have it statted as the lab test article, which the new model will look nothing like - or, treat it as a theoretical/extrapolated part with its design target performance numbers (19,300s Isp, 2.5 N thrust, 250 kW power, unknown mass)?

**Comment by PhineasFreak** [comment]
Because actual flight hardware does not exist yet you can just scale and balance them according to current test articles.

The "negative" alternator is a workaround, probably because setting the correct "O/F" ratio (the ratio between the required ElectricCharge and the propellant) does not lead to sane values. Regardless, you can test it by changing the ratios and see if it makes any sense (i had tried to do this with the stock ion engine).

**Comment by lOmicronl** [comment]
How does it not lead to sane values? I've been managing the NF engines that way for two years. And not once have I failed to give them the power draw I wanted them to have.

You just need to realize that what you are setting is not a power draw, but rather a volume flow ratio. If your main propellant has a ratio of 1 and Ec has a ratio of 50, then for 1 volume unit of propellant that flows, 50 (volumeless) units of Ec flow.

Using the density of the propellant, you can convert the volume flow rate into a mass flow rate, and the mass flow rate is a direct result of thrust and specific impulse. Thus, it's perfectly viable to calculate the correct ratio for any given desired power draw by hand.

And then, of course, there's being lazy and just measuring the deviation to the desired goal, and applying it as a multiplier to the ratio... :P

**Comment by Max-Q** [comment]
I just committed a fix for the NEXT ion engines. I think all other engines are broken because the trick with the alternator having negative values does not work (in my installation with KSP 1.2.2).

**Comment by pap1723** [comment]
This is outdated. If someone is interested in Near Future stuff, they can open an issue in the future.
