### ISSUE TITLE
Holding parts to historically known volumes where we can

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RealismOverhaul#745]
RedAV8R started a conversation on a PR that warrants further discussion and linking of data:
https://github.com/KSP-RO/RealismOverhaul/pull/739

**Comment by stratochief66** [comment]
Currently the Gemini SM(s) have more reactants for the fuel cell than they historically should have:
https://github.com/KSP-RO/RealismOverhaul/blob/fasa-gemini-sm/GameData/RealismOverhaul/RO_SuggestedMods/FASA/RO_FASA_Gemini_Pod.cfg#L632-L643

Thanks RedAV8R for giving me the name that helped find a decent source. Previously, I had estimated the Gemini reactants based on a source I found for Apollo fuel cell reactants.

https://en.wikisource.org/wiki/NASA_Project_Gemini_Familiarization_Manual#REACTANT_SUPPLY_SYSTEM

A max of 22.25 lbs of LH2 translates to 10.09 kg, which is 142.45 L. 
A max of 180 lbs of LO2 translates to 81.65 kg, which is 71.56 L.

**Comment by stratochief66** [comment]
Both the old (RedAV8R) and newer (stratochief66) values differ substantially from this source.
https://github.com/KSP-RO/RealismOverhaul/commit/3f346ce3ed96ef1d02537b05110f39d857d622da#diff-b84809538c5bcc439151f082436dc134L782

**Comment by stratochief66** [comment]
The Gemini is quite unique, in that it flew both versions with no fuel cells or reactants at all (other than liquid breathing gases)

Since FASA provides two separate parts that both represent the Gemini SM, it might make sense to set one up with the dry & filled masses of a non-fuel cell SM, and the other one as a SM with fuel cells. I imagine the dry weights of these two could vary substantially (batteries vs fuel cells & reactant tanks), If someone could find and link citations for those masses (and include the masses in their post) that would be helpful.

**Comment by stratochief66** [comment]
The TACLS input/output values for the Gemini SM will need adjusting to work correctly with any changes to the reactants available. I can do that once we have found sources and settled on final reactant volumes.

**Comment by RedAV8R** [comment]
It would be better to copy parts for the Gemini SM because the two parts are not equal in transforms for RCS or at least one has engines built into it rather than the retro module.

As for values not matching. I think we took middle ground. Some Gemini flew with 106lbs of LOX, some with 46lbs, while the one flew with 180lbs. Some flew with 22.5lbs of LH2 some flew with a mere 5.8 lbs. So we can either develop copies for each mission. Or set a max, let the user decide how much. Or...would have to look into it. Like Procedural Parts changes tank type. We could create some tank types for each mission, then change tank type like Procedural parts does, which 'should' be able to change the tank configuration as needed.

**Comment by stratochief66** [comment]
One really nice thing about the proctanks is that the amount of resource can be adjusted very easily, which allows the users to reproduce missions of different lengths quite easily.

With proctanks as they currently are, I believe it makes sense to setup a craft/part to have a max capacity of the longest mission type performed, which can be adjusted using the sliders.
