### ISSUE TITLE
New Engine Templates - Add Relights & Ullage?

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RealismOverhaul#869]
@SirKeplan 's engine templating system is coming along very well! I was wondering what other engine features make sense to tie into a template.

Mass makes sense, SirKeplan has already done that I believe, and has a trick to override it for parts where it does not make sense (for instance, the Trans-stage where the tanks are part of the same part with the engine) ignoreMass = true

Multi-engine configs make sense, and SirKeplan has already implemented that with engineTypeMult = 2

@SirKeplan, would it be possible to move the ullage and relights components over to the templates as well?

This would be particularly timely, since we are planning to do a review pass of relights as a near-term upcoming major project, and having to only implement it in one place would be super handy, and clear.

Could this be added to the existing outstanding PRs, or no?

**Comment by PhineasFreak** [comment]
@stratochief66 @SirKeplan if you don't mind replying, ullage sim parameters are definitely candidates for including with the global engine configs. That way one should not be afraid if the parameters are correct or not (see the issue with the J-2 ignitions for an example).

Also, the "heatProduction" field is another good candidate but for removal from the global system. Each engine config from a specific family could have different thermal parameters depending on the application (like the LR-87 that has both hypergolic and cryogenic abilities in it's "family tree").

I have experimented with the above examples extensively and i can say that they are easy to implement and they improve a lot the concept of globalization.

**Comment by stratochief66** [comment]
@PhineasFreak heat production, I could see that making sense. I'm not sure what syntax would work for that, just a %heatProduction = I suppose?

What about gimbal? that might need an override for clusters that have a different gimbal values than the single engine configs.

**Comment by PhineasFreak** [comment]
Oh, you were quick, i deleted the heat production comment because on a second thought i found it a bit stupid...that could be applied by a multiplier (like "engineHeatMult" or something like that) for multi - engine components. Then, a global patch as with the mass offsets, thrust multipliers etc.

Hmm, i had forgotten about the gimbal ranges. I guess it could also be applied via a global patch where the global engine config can insert the baseline gimbal range but it can be overriden by a "useCustomGimbal = <BOOLEAN>" switch and a "engineGimbalRange = <FLOAT> parameter.

**Comment by SirKeplan** [comment]
I originally thought gimbal would be tricky to do. But as you say there's gimbal range in moduleengineconfigs, and some of my files already use it. So that should be worth using.

**Comment by NathanKell** [comment]
There is no particular reason you can't include non-ModuleEngineConfigs stuff in each patch, so you needn't even use the MEC gimbal parameter. I highly recommend including basically everything engine related that would otherwise be copy-pasted.

**Comment by PhineasFreak** [comment]
That would also work wonders for engines that require an ignition type other than electricity, like TEATEB, Peroxide, Helium, Nitrogen etc.

**Comment by stratochief66** [comment]
@SirKeplan, could you possibly start adding things like ullage and relights to yours PRs as you go now?

**Comment by NathanKell** [comment]
A note on this:
In most circumstances, it would be best if all engine-related stuff is in the global config. That is to say title, description, mass, any changes to ModuleEngines (like making it ModuleEnginesRF, adding ullage/pfed/ignitions, etc), any RESOURCE nodes added for ignition resource use, any Gimbal changes, and finally the ModuleEngineCongfigs module(s). I use (s) because some engine parts have (or have added by RO) multiple ModuleEngines, one for the main engine and one for verniers. In these cases the ModuleEngines* patches need a HAS to target the correct module, and same with the gimbal changes. I am not sure (and I think it does not) make sense to actually add the new ModuleEngines and the new ModuleGimbal in the global config; instead stubs should be added locally. But the *ordering* should be preserved to always be main first, vernier second.

Then any part-specifc changes can be done in an AFTER pass (like changing origMass for clusters or for tankbutted engines, changing thrust for clusters, removing excess CONFIGs).

That brings me to another point. I was thinking about parts where we want only certain CONFIGs available. Since AFAIK ModuleManager does not support OR in subnode HAS blocks, let alone variables in HAS blocks, this is nontrivial. However, there is a way around this, though I am not certain it is worth the hassle. Consider:
@PART[foo]
{
engineType = bar
exlcudeConfig = baz
excludeConfig = bing
}
@PART[foo]:FOR[engine adding]
{
Insert MEC
}
@PART[foo]AFTER{engine adding]:HAS[#excludeConfig[baz]]
{
@MEC
{
!CONFIG[baz] {}
}

A similar approach could be done with includeConfig, replacing the single add-MEC pass with one pass per config.

**Comment by SirKeplan** [comment]
@stratochief66 will do ,future PRs will include ullage etc.

@NathanKell i'm unsure, it looks a bit like that might not be worth the effort, unless the code was somehow autogenerated perhaps.
It would be easier if as you say could MM support OR in HAS blocks.

**Comment by NathanKell** [comment]
Autogenerating it is trivial, but I agree it's not really less effort than doing an AFTER for the specific part, as we discussed when this came up before.

**Comment by SirKeplan** [comment]
Title and description wont always want to follow the global config, as the part may be a different diameter, or may be a whole rocket stage instead of just an engine etc. That's why i had left them out/not mentioned them yet.

Do you think it's better to put them in, and then do overrides when needed then?

**Comment by NathanKell** [comment]
Very much better. I sure as heck don't want to fix the LR79's description five times every time I change it. :)

**Comment by raidernick** [comment]
I noticed that you are including gimbal into the mater engine configs. How is this going to work for engines that don't use the stock gimbal module. This will end up adding double gimbals to the same engine.

**Comment by SirKeplan** [comment]
Ah, good point, that could be tricky, hmmmm. do you have an example of an engine that uses a different gimbal module?

**Comment by SirKeplan** [comment]
ah, i see https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/CSS/RO_CSS.cfg
 has a different gimbal module for a start. 

i suppose one solution to this would be to patch those engines in a `:AFTER[RealismOverhaulEngines]` block just simply removing the stock gimbal module in that block.

**Comment by NathanKell** [comment]
A @MODULE[ModuleGimbal] patch will quietly and happily fail if no such module exists, so there is no need to worry about AFTER passes. If a part uses a nonstandard gimbal, it will just keep being patched the way it always has been, in the local cfg.

**Comment by SirKeplan** [comment]
ah yes, of course it will :D

**Comment by PhineasFreak** [comment]
We might have an issue with the gimbals, some engines have multiple modules that represent vernier thrusters or exhausts. For example, the RS-68 from CryoEngines has one but the AIES, Baha & CMES do not. Although it would be much better if we could add an engine transform to them.

**Comment by SirKeplan** [comment]
@PhineasFreak nathankell mentioned that as a possible problem, for the minute I’m not doing any more editing of engines with verniers.

**Comment by PhineasFreak** [comment]
A solution to this problem would be to have a global engine gimbal for all available gimbal transforms:

```
@MODULE[ModuleGimbal],*
{
     @gimbalRange = FLOAT
     %useGimbalResponseSpeed = True
     %gimbalResponseSpeed = 16
}
```
The verniers then will be patched in an "after" pass, like some other engines.

**Comment by NathanKell** [comment]
I would suggest just leaving verniers alone to start with, and only patching the first ModuleGimbal. IMO the ,* creates more problems than it solves.

**Comment by PhineasFreak** [comment]
Some configs that i have seen have the first gimbal module as the vernier so this would not be much better. I would suggest dropping the gimbal patching altogether.

**Comment by NathanKell** [comment]
I would suggest only dropping patching engines with verniers atm. Gimbal is a core property of an engine, just as much as thrust and Isp and mass are, and really should not be left per-part-patch if we can help it. The point of this overhaul is to centralize as much as possible such that when new info comes to light and we make corrections, we *only have to do them once*.

**Comment by stratochief66** [comment]
Pending closing, I think this conversation concluded. Pending resolution/closing of #939 as well.

**Comment by NathanKell** [comment]
Closing this, leaving #939 open.
