### ISSUE TITLE
RN proton and r7 configs

### ISSUE THREAD

**Issue by raidernick** [KSP-RO/RealismOverhaul#875]
I am making this issue to remind myself that my proton and r7 engine configs need to be revised, specifically the mix rates of some of them and the tank values altered appropriately.

**Comment by raidernick** [comment]
proton fixed, reminder for r7 configs still

**Comment by stratochief66** [comment]
Just so you now the steps the SirKeplan engine template system will be going through.

1 (Current): Creating templates for engine configs, moving modes over to using those templates.
2: Moving ignitions and other pertinent engine data (ie. possibly gimbal) over to the template as well.
3. A review pass of major engines / engines that require a deeper review so we know we have solid, cited data sources for the engine thrusts and ISPs.
4. The next sizeable project, which is reviewing engines to abide by a relight standard that @NathanKell defines.

If a part has been moved to a template, that template may change in step 3, so changes to an integrated tank/engine part (ie. many of the RN parts) might need to be done twice if you want it to use the templates.

That said, all mods don't need to make use of the new templates. I definitely see them being more of a pain for some parts compared to others that are just engines that will get used with proctanks.

SInce there has already been considerable discussion occuring over at #874, I would suggest listing which mods (by RO folder if possible) you consider to be RN mods that you don't want to be moved over to templates right now so that we don't touch them.

**Comment by raidernick** [comment]
@stratochief66 as I posted in the other thread, I don't want any of them touched, if/when I do it I'll make the move myself. This issue is not related to those changes at all, it's related to the major model/config changes my base packs are undergoing right now. I am basically redoing them from scratch.
