### ISSUE TITLE
Gemini Fuel and Retro Pack fuel issue

### ISSUE THREAD

**Issue by Aberro** [KSP-RO/RealismOverhaul#885]
Gemini Fuel and Retro Pack have engine that uses PBAN, but no PBAN resource (and cannot switch tanks to use PBAN in Real Fuels).

**Comment by stratochief66** [comment]
https://github.com/KSP-RO/RealismOverhaul/blob/46d1ddb8852f487134e1e496d7292022f7567a24/GameData/RealismOverhaul/RO_SuggestedMods/Tantares/RO_Tantares_Gemini.cfg#L312-L340

The code for that all looks pretty normal. Can you post your MM log? (ModuleManager.ConfigCache)

**Comment by stratochief66** [comment]
Hmm, the issue might be that you cannot add PBAN to a service module type tank,even if you manually force it in the config. That file might clarify that.

Also, paging @Niemand303 :)

**Comment by Aberro** [comment]
[ModuleManager.ConfigCache.txt](https://github.com/KSP-RO/RealismOverhaul/files/110992/ModuleManager.ConfigCache.txt)

**Comment by stratochief66** [comment]
Hmm, the PBAN shows up in the tank in the MM Cache. @NathanKell would it still now show up if tank type "ServiceModule" was not allowed to store PBAN?

**Comment by NathanKell** [comment]
ModuleFuelTank modules only clear resources that they can handle. ServiceModule won't remove PBAN. Same reason the Bonanza cockpit doesn't remove food.

**Comment by Aberro** [comment]
So, what should I do to fix this? 
Btw, isn't PBAN should be solid fuel?

**Comment by stratochief66** [comment]
@Aberro you haven't even stated what mod you are got your Gemini from, so I don't know how you would expect us to be able to help you.

From the MM cache, it looks like a bunch of Tantares parts are showing up, while I would assume you were using FASA since that is the only mod I had been aware had a substantially modelled Gemini.

so @Aberro, tell us what mod you got your Gemini from. It looks like @Niemand303 did the Tantares Gemini configs. Can you look into this @Niemand303 ?
https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/Tantares/RO_Tantares_Gemini.cfg

**Comment by Aberro** [comment]
@stratochief66 yes, it's from tantares mod (though, I have FASA too; I've installed most mods from recommended and suggested mods list from CKAN and then removed some of them to fit memory limits) and this part is modified by the config file you referenced to.
